#!/bin/sh


# $Id$
# Copyright (C) 2004 The Xastir Group


echo
echo
echo
echo Please note that a subdirectory called "xastir" will be created
echo here and populated with the latest Xastir source code.  If you
echo already have an "xastir" directory and are running the script
echo from there, you may want to run it from one directory higher up
echo instead.  Just stop this script and run these commands instead:
echo
echo "    cd .."
echo "    ./xastir/install-xastir"
echo
echo Press ENTER to continue downloading the latest Xastir sources:
read


# Set up an anonymous login for the CVS server
#
echo
echo Press the ENTER key when asked for the CVS password below:
cvs -d:pserver:anonymous@cvs.sourceforge.net:/cvsroot/xastir login


# Fetch the latest Xastir sources
#
cvs -d:pserver:anonymous@cvs.sourceforge.net:/cvsroot/xastir co xastir


# Run the update script to configure/compile/install it
#
cd xastir; ./update-xastir


echo
echo
echo
echo If you have set up the /etc/sudoers file as described in README.CVS, you should
echo now have Xastir compiled and installed, else go set up the /etc/sudoers file,
echo then type the update-xastir command as listed below.  Run:
echo
echo "    callpass"
echo
echo To get your passcode.  You will need the number it computes in order to
echo authenticate with the internet servers.  Run Xastir by typing:
echo
echo "    xastir &"
echo
echo To update Xastir to the latest CVS version at any time, change
echo to the "xastir" directory and type:
echo
echo "    ./update-xastir"
echo


