#! /bin/sh


# $Id$
# Copyright (C) 2004-2010 The Xastir Group

# See README.CVS for instructions on setting up SUDO for
# Linux/Unix/MacOSX systems, specifically the /etc/sudoers file.


CYGWIN=false
uname=`uname`

case "$uname" in
    CYGWIN*)
        CYGWIN=true
        ;;
    *)
        ;;
esac


(date 2>&1)                               | tee    make.log
(cvs update -P -d 2>&1)                   | tee -a make.log

echo ""                                   | tee -a make.log
echo ""                                   | tee -a make.log
(date 2>&1)                               | tee -a make.log
(./bootstrap.sh 2>&1)                     | tee -a make.log

echo ""                                   | tee -a make.log
echo ""                                   | tee -a make.log
(date 2>&1)                               | tee -a make.log
(./configure 2>&1)                        | tee -a make.log

echo ""                                   | tee -a make.log
echo ""                                   | tee -a make.log
(date 2>&1)                               | tee -a make.log


if $CYGWIN
then
    (echo "************************************") | tee -a make.log
    (echo "Building for Cygwin Operating System") | tee -a make.log
    (echo "************************************") | tee -a make.log
    (make clean 2>&1)                     | tee -a make.log

    echo ""                               | tee -a make.log
    echo ""                               | tee -a make.log
    (date 2>&1)                           | tee -a make.log
    (make install 2>&1)                   | tee -a make.log
#    chmod 4755 /usr/local/bin/xastir
    chmod 755 /usr/local/bin/xastir

    echo ""                               | tee -a make.log
    (date 2>&1)                           | tee -a make.log
else
    (echo "************************************************") | tee -a make.log
    (echo "Building for Unix/Linux/MacOSX Operating Systems") | tee -a make.log
    (echo "************************************************") | tee -a make.log
    (sudo make clean 2>&1)                | tee -a make.log

    echo ""                               | tee -a make.log
    echo ""                               | tee -a make.log
    (date 2>&1)                           | tee -a make.log 
    (make 2>&1)                           | tee -a make.log
    (sudo make install-strip 2>&1)        | tee -a make.log
#    sudo chmod 4755 /usr/local/bin/xastir
    sudo chmod 755 /usr/local/bin/xastir

    echo ""                               | tee -a make.log
    (date 2>&1)                           | tee -a make.log
fi


