#! /bin/sh


# $Id$
# Copyright (C) 2004 The Xastir Group

# See README.CVS for instructions on setting up SUDO, specifically
# the /etc/sudoers file.  Windows/Cygwin users shouldn't need sudo
# and can just delete the sudo keyword from the lines below.


cvs update
./bootstrap.sh
./configure --without-errorpopups
sudo make clean
sudo make install
sudo chmod 4755 /usr/local/bin/xastir

