.TH XASTIR 1 " Apr 09 2002" "By Jose HI8GN on" "Xastir APRS Client APPL"
.SH NAME
Xastir is a graphical application that interfaces HAM radio
and internet access to real-time mapping software.

.SH SYNOPSIS
.B xastir
.I "[options] Languages ..."
.TP
.SH OPTIONS
The program follows the usual GNU command line syntax, with long
options starting with one dash (`-').
A summary of options is included below.
.br
.B \-vlevel
Set the debug level
.br
.B \-l, \-lLanguage
Show summary of options available.
.SH AVAILABLE LANGUAGES
Current choices are:
.B Dutch English French German Italian Portuguese
and
.B Spanish.
.SH Usage is:
.br
.B xastir -lDutch
.br
.B xastir -lEnglish
.br
.B xastir -lFrench
.br
.B xastir -lGerman
.br
.B xastir -lItalian
.br
.B xastir -lSpanish
.SH "SEE ALSO"
The program is documented fully by
.IR "help.English.dat" ,
available via the HELP menu option.
.br
.SH "DESCRIPTION"
This manual page documents briefly the
.BR xastir
commands.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
Instead, it has documentation in the GNU Info format; see below.
.PP
.B xastir
is a program for APRS...
.br
.PP
.B APRS[tm]
.br
is a Trademark of Bob Bruninga, his home page is at
"http://web.usna.navy.mil/~bruninga/aprs.html"

.SH AUTHOR
This manual page was written by Jose Marte <hi8gn@amsat.org>,
for the Debian GNU/Linux system (but may be used by others).
.br
.SH COPYING
Copyright (C) 1999,2000 Frank Giannandrea KC2GJS
Copyright (C) 2000,2001,2002 The Xastir Group
