.TH XASTIR 1 "HI8GN on Apr 09 2002" "By Jose R. Marte A." "Xastir APRS(tm) Client APPLICATION"
.SH NAME
Xastir \- graphical application that interfaces HAM radio
and APRS(tm) internet access to real-time mapping software.
.SH "DESCRIPTION"
This manual page briefly documents the
.BR Xastir
commands.
.SH SYNOPSIS
.B xastir
.I "[options] Language ..."
.SH OPTIONS
The program follows the usual GNU command line syntax, with long
options starting with one dash (`-').
A summary of options is included below.
.TP
.br
.B \-c /path/dir
Specify an optional config directory. Defaults to ~/.xastir
.TP
.br
.B \-f callsign
Track callsign
.TP
.br
.B \-i
Use a private colormap
.TP
.br
.B \-geometry WxH+x+y
Set Window Geometry/Position
.TP
.br
.B \-l Language
Xastir remembers the language once you set it the first time.
.TP
.br
.B \-m
Deselect Maps
.TP
.br
.B \-p
Disable popups
.TP
.br
.B \-t
Internal SIGSEGV handler enabled
.TP
.br
.B \-v Level
Set the debug level
.TP
.br
.B \-?
Show summary of options available.
.br
.SH AVAILABLE LANGUAGES
Current choices are:
.br
.B Dutch English French German Italian Portuguese Spanish.
.SH Usage is:
.br
.B xastir -i -v 2047 -l Dutch &
.br
.SH SIGNALS
.B SIGINT, SIQQUIT, SIGTERM
Cause Xastir to exit.
.br
.B SIGHUP
Causes a restart.
.br
.B SIGUSR1
Causes a snapshot to occur.
.br
.SH NETWORK PORTS
Enable these ports on this menu:  "Interface->Enable Server Ports"
.br
.PP
.B TCP:2023
Bidirectional TCP port for clients to connect to.  Requires login if
client will be transmitting.
.br
.B UDP:2023
Unidirectional UDP input port for clients to inject packets.  See
the documentation for the format.
.br
.SH "SEE ALSO"
The program is documented fully by
.IR "help-English.dat" ,
available via the HELP menu option in Xastir, plus the various
README and INSTALL text files that come with the program.  Also see
<http://www.xastir.org> and the Documentation Wiki there.
.br
.PP
.B Xastir
is a program for APRS(tm)...
.br
.PP
.B APRS[tm]
is a Trademark of Bob Bruninga, his home page is at
"http://www.aprs.org/aprs.html"
.SH COPYING
Copyright (C) 1999,2000 Frank Giannandrea KC2GJS
.br
Copyright (C) 2000-2012 The Xastir Group
.SH AUTHOR
This manual page was written by Jose <hi8gn@amsat.org>,
for the Debian GNU/Linux system (but may be used by others).
