/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created
**      by: Qt User Interface Compiler version 4.8.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QDialogButtonBox>
#include <QtGui/QHBoxLayout>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QStatusBar>
#include <QtGui/QTabWidget>
#include <QtGui/QToolBar>
#include <QtGui/QToolButton>
#include <QtGui/QVBoxLayout>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionPrint;
    QAction *actionOpen_Log_File;
    QAction *actionTNC_Logging;
    QAction *actionNet_Logging;
    QAction *actionIGate_Logging;
    QAction *actionMessage_Logging;
    QAction *actionWX_Logging;
    QAction *actionWX_Alert_Logging;
    QAction *actionPNG_Snapshots;
    QAction *actionKML_Snapshots;
    QAction *actionE_xit;
    QAction *action_Incoming_Data;
    QAction *actionMessage_Traffic;
    QAction *action_Bulletins;
    QAction *action_Mobile_Stations;
    QAction *action_All_Stations;
    QAction *actionLocal_Stations;
    QAction *action_Last_Stations;
    QAction *actionObjects_Items;
    QAction *actionOwn_Objects_Items;
    QAction *actionCAD_Polygons;
    QAction *action_Weather_Stations;
    QAction *actionOwn_Weather_Data;
    QAction *actionW_eather_Alerts;
    QAction *actionGPS_Status;
    QAction *action_Uptime;
    QAction *actionALOHA_Statistics;
    QAction *action_Map_Chooser;
    QAction *actionMap_Display_Bookmarks;
    QAction *actionLocate_Map_Feature;
    QAction *actionFind_Address;
    QAction *actionCoordinate_Calculator;
    QAction *actionCenter_Zoom;
    QAction *actionDisable_Fast_Zoom_Pan_Home;
    QAction *actionDisable_All_Maps;
    QAction *actionEnable_Auto_Maps;
    QAction *actionAuto_Map_Disable_Raster_Maps;
    QAction *actionEnable_Map_Grid;
    QAction *actionEnable_Map_Border;
    QAction *actionEnable_Map_Levels;
    QAction *actionEnable_Map_Labels;
    QAction *actionEnable_Area_Color_Fills;
    QAction *actionEnable_Weather_Alerts;
    QAction *actionMouse_Pointer_Menu;
    QAction *action_Find_Stations;
    QAction *action_Track_Station;
    QAction *actionFetch_Find_u_Trail;
    QAction *action_Send_Message_To;
    QAction *actionShow_Pending_Messages;
    QAction *action_Open_Group_Messages;
    QAction *action_Clear_All_Outgoing_Messages;
    QAction *action_General_Stations_Query;
    QAction *action_IGate_Stations_Query;
    QAction *action_WX_Stations_Query;
    QAction *actionModify_Auto_Reply_Message;
    QAction *actionEnable_Auto_Reply_Message;
    QAction *actionSatellite_Ack_Mode;
    QAction *action_About;
    QAction *actionHelp_Index;
    QAction *actionInterface_Control;
    QAction *actionDisable_Transmit_ALL;
    QAction *actionDisable_Transmit_My_Position;
    QAction *actionDisable_Transmit_Objects_Items;
    QAction *actionEnable_Server_Ports;
    QAction *action_Transmit_Now;
    QAction *action_Fetch_GPS_Track;
    QAction *actionFetch_GPS_Routes;
    QAction *actionFetch_GPS_Waypoints;
    QAction *actionFetch_Garmin_RINO_Waypoints;
    QAction *action_EMERGENCY_BEACON_MODE;
    QAction *action_Station;
    QAction *action_Defaults;
    QAction *action_Timing;
    QAction *actionC_oordinate_System;
    QAction *action_Audio_Alarms;
    QAction *actionS_peech;
    QAction *actionSmart_Beaconing;
    QAction *actionFonts;
    QAction *actionTest;
    QAction *actionChange_Debug_Level;
    QAction *actionEnable_English_Units;
    QAction *actionDist_Bearing_Status;
    QAction *actionSave_Config_Now;
    QAction *actionClose_Polygon;
    QAction *actionErase_CAD_Polygons;
    QAction *actionCAD_Polygons_2;
    QAction *actionEnable_CAD_objects;
    QAction *actionEnable_CAD_labels;
    QAction *actionEnable_CAD_probability;
    QAction *actionEnable_CAD_comments;
    QAction *actionEnable_CAD_area_size;
    QAction *actionAdjust_Gamma_Correction;
    QAction *actionConfigure_Tigermap;
    QAction *actionConfigure_USGS_DRG;
    QAction *actionRe_download_Maps_Not_from_cache;
    QAction *actionFlush_Entire_Map_Cache;
    QAction *actionIndex_New_Maps_on_Startup;
    QAction *actionIndex_Add_New_Maps;
    QAction *actionIndex_Reindex_ALL_Maps;
    QAction *actionWhite;
    QAction *actionBlack;
    QAction *actionGray;
    QAction *actionMisty_Rose;
    QAction *actionNavy_Blue;
    QAction *actionSteel_Blue;
    QAction *actionMed_Sea_Green;
    QAction *actionPale_Green;
    QAction *actionPale_Goldenrod;
    QAction *actionGoldenrod_Yellow;
    QAction *actionRosy_Brown;
    QAction *actionFirebrick_Red;
    QAction *action0;
    QAction *action10;
    QAction *action20;
    QAction *action30;
    QAction *action40;
    QAction *action50;
    QAction *action60;
    QAction *action70;
    QAction *action80;
    QAction *action90;
    QAction *action100;
    QAction *action_Black_Border;
    QAction *actionBlack_Shadow;
    QAction *action_Text_on_Black;
    QAction *action_No_Outline;
    QAction *action_Black_Outline;
    QAction *action_Grey_Outline;
    QAction *action_White_Outline;
    QAction *actionExport_to_KML_File;
    QAction *actionSelect_None;
    QAction *actionSelect_Mine;
    QAction *actionSelect_TNC;
    QAction *action_Select_Direct;
    QAction *action_Select_Via_Digi;
    QAction *actionSelect_Net;
    QAction *actionSelect_Tactical_Calls_Only;
    QAction *actionInclude_Expired_Data;
    QAction *actionSelect_Stations;
    QAction *action_Select_Fixed_Stations;
    QAction *action_Select_Moving_Stations;
    QAction *action_Select_WX_Stations;
    QAction *action_Select_CWOP_WX_Stations;
    QAction *actionSelect_Objects_Items;
    QAction *action_Select_WX_Objects_Items;
    QAction *action_Select_Water_Gauge_Objects_Items;
    QAction *action_Select_Other_Objects_Items;
    QAction *actionDisplay_Callsign;
    QAction *action_Label_Trailpoints;
    QAction *actionDisplay_Symbol;
    QAction *action_Rotate_Symbol;
    QAction *actionDisplay_Trail;
    QAction *actionDisplay_Course;
    QAction *actionDisplay_Speed;
    QAction *action_Display_Short_Speed;
    QAction *actionDisplay_Altitude;
    QAction *actionDisplay_Weather_Info;
    QAction *action_Display_Weather_Text;
    QAction *action_Temperature_Only;
    QAction *action_Display_Wind_Barb;
    QAction *actionDisplay_Aloha_Circle;
    QAction *actionDisplay_Position_Ambiguity;
    QAction *actionDisplay_Power_Gain;
    QAction *action_Use_Default_Power_Gain;
    QAction *action_Display_Mobile_Power_Gain;
    QAction *actionDisplay_DF_Attributes;
    QAction *actionDisplay_DF_Beamwidth;
    QAction *actionDisplay_DF_Bearing;
    QAction *actionEnable_Dead_Reckoning;
    QAction *action_Display_Arc;
    QAction *action_Display_Course;
    QAction *action_Display_Symbol;
    QAction *actionDIsplay_Dist_Bearing;
    QAction *actionDisplay_Last_Report_Age;
    QAction *actionReload_Object_Item_History;
    QAction *actionClear_Object_Item_History;
    QAction *actionClear_All_Tactical_Calls;
    QAction *actionClear_Tactical_Call_History;
    QAction *action_Clear_All_Trails;
    QAction *actionClear_All_Stations;
    QWidget *centralWidget;
    QHBoxLayout *horizontalLayout;
    QTabWidget *tabWidget;
    QWidget *Map1;
    QVBoxLayout *verticalLayout;
    QLabel *incomingPackets;
    QWidget *Map2;
    QToolButton *toolButton;
    QWidget *Map3;
    QCheckBox *checkBox;
    QWidget *Map4;
    QDialogButtonBox *buttonBox;
    QMenuBar *menuBar;
    QMenu *menuFile;
    QMenu *menu_Configure;
    QMenu *menuView;
    QMenu *menuMap;
    QMenu *menuDraw_CAD_Objects;
    QMenu *menuConfigure;
    QMenu *menuBackground_Color;
    QMenu *menuMap_Intensity;
    QMenu *menuStation_Text_Style;
    QMenu *menuIcon_Outline_Style;
    QMenu *menuStation;
    QMenu *menu_Export_All;
    QMenu *menuFilter_Data;
    QMenu *menuFilter_Display;
    QMenu *menuConfigure_2;
    QMenu *menuMessage;
    QMenu *menuInterface;
    QMenu *menuHelp;
    QMenu *menu_EMERGENCY_BEACON_MODE_ENABLE;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1036, 526);
        actionPrint = new QAction(MainWindow);
        actionPrint->setObjectName(QString::fromUtf8("actionPrint"));
        actionOpen_Log_File = new QAction(MainWindow);
        actionOpen_Log_File->setObjectName(QString::fromUtf8("actionOpen_Log_File"));
        actionTNC_Logging = new QAction(MainWindow);
        actionTNC_Logging->setObjectName(QString::fromUtf8("actionTNC_Logging"));
        actionTNC_Logging->setCheckable(true);
        actionNet_Logging = new QAction(MainWindow);
        actionNet_Logging->setObjectName(QString::fromUtf8("actionNet_Logging"));
        actionNet_Logging->setCheckable(true);
        actionIGate_Logging = new QAction(MainWindow);
        actionIGate_Logging->setObjectName(QString::fromUtf8("actionIGate_Logging"));
        actionIGate_Logging->setCheckable(true);
        actionMessage_Logging = new QAction(MainWindow);
        actionMessage_Logging->setObjectName(QString::fromUtf8("actionMessage_Logging"));
        actionMessage_Logging->setCheckable(true);
        actionWX_Logging = new QAction(MainWindow);
        actionWX_Logging->setObjectName(QString::fromUtf8("actionWX_Logging"));
        actionWX_Logging->setCheckable(true);
        actionWX_Alert_Logging = new QAction(MainWindow);
        actionWX_Alert_Logging->setObjectName(QString::fromUtf8("actionWX_Alert_Logging"));
        actionWX_Alert_Logging->setCheckable(true);
        actionPNG_Snapshots = new QAction(MainWindow);
        actionPNG_Snapshots->setObjectName(QString::fromUtf8("actionPNG_Snapshots"));
        actionPNG_Snapshots->setCheckable(true);
        actionKML_Snapshots = new QAction(MainWindow);
        actionKML_Snapshots->setObjectName(QString::fromUtf8("actionKML_Snapshots"));
        actionKML_Snapshots->setCheckable(true);
        actionE_xit = new QAction(MainWindow);
        actionE_xit->setObjectName(QString::fromUtf8("actionE_xit"));
        action_Incoming_Data = new QAction(MainWindow);
        action_Incoming_Data->setObjectName(QString::fromUtf8("action_Incoming_Data"));
        actionMessage_Traffic = new QAction(MainWindow);
        actionMessage_Traffic->setObjectName(QString::fromUtf8("actionMessage_Traffic"));
        action_Bulletins = new QAction(MainWindow);
        action_Bulletins->setObjectName(QString::fromUtf8("action_Bulletins"));
        action_Mobile_Stations = new QAction(MainWindow);
        action_Mobile_Stations->setObjectName(QString::fromUtf8("action_Mobile_Stations"));
        action_All_Stations = new QAction(MainWindow);
        action_All_Stations->setObjectName(QString::fromUtf8("action_All_Stations"));
        actionLocal_Stations = new QAction(MainWindow);
        actionLocal_Stations->setObjectName(QString::fromUtf8("actionLocal_Stations"));
        action_Last_Stations = new QAction(MainWindow);
        action_Last_Stations->setObjectName(QString::fromUtf8("action_Last_Stations"));
        actionObjects_Items = new QAction(MainWindow);
        actionObjects_Items->setObjectName(QString::fromUtf8("actionObjects_Items"));
        actionOwn_Objects_Items = new QAction(MainWindow);
        actionOwn_Objects_Items->setObjectName(QString::fromUtf8("actionOwn_Objects_Items"));
        actionCAD_Polygons = new QAction(MainWindow);
        actionCAD_Polygons->setObjectName(QString::fromUtf8("actionCAD_Polygons"));
        action_Weather_Stations = new QAction(MainWindow);
        action_Weather_Stations->setObjectName(QString::fromUtf8("action_Weather_Stations"));
        actionOwn_Weather_Data = new QAction(MainWindow);
        actionOwn_Weather_Data->setObjectName(QString::fromUtf8("actionOwn_Weather_Data"));
        actionW_eather_Alerts = new QAction(MainWindow);
        actionW_eather_Alerts->setObjectName(QString::fromUtf8("actionW_eather_Alerts"));
        actionGPS_Status = new QAction(MainWindow);
        actionGPS_Status->setObjectName(QString::fromUtf8("actionGPS_Status"));
        action_Uptime = new QAction(MainWindow);
        action_Uptime->setObjectName(QString::fromUtf8("action_Uptime"));
        actionALOHA_Statistics = new QAction(MainWindow);
        actionALOHA_Statistics->setObjectName(QString::fromUtf8("actionALOHA_Statistics"));
        action_Map_Chooser = new QAction(MainWindow);
        action_Map_Chooser->setObjectName(QString::fromUtf8("action_Map_Chooser"));
        actionMap_Display_Bookmarks = new QAction(MainWindow);
        actionMap_Display_Bookmarks->setObjectName(QString::fromUtf8("actionMap_Display_Bookmarks"));
        actionLocate_Map_Feature = new QAction(MainWindow);
        actionLocate_Map_Feature->setObjectName(QString::fromUtf8("actionLocate_Map_Feature"));
        actionFind_Address = new QAction(MainWindow);
        actionFind_Address->setObjectName(QString::fromUtf8("actionFind_Address"));
        actionCoordinate_Calculator = new QAction(MainWindow);
        actionCoordinate_Calculator->setObjectName(QString::fromUtf8("actionCoordinate_Calculator"));
        actionCenter_Zoom = new QAction(MainWindow);
        actionCenter_Zoom->setObjectName(QString::fromUtf8("actionCenter_Zoom"));
        actionDisable_Fast_Zoom_Pan_Home = new QAction(MainWindow);
        actionDisable_Fast_Zoom_Pan_Home->setObjectName(QString::fromUtf8("actionDisable_Fast_Zoom_Pan_Home"));
        actionDisable_Fast_Zoom_Pan_Home->setCheckable(true);
        actionDisable_All_Maps = new QAction(MainWindow);
        actionDisable_All_Maps->setObjectName(QString::fromUtf8("actionDisable_All_Maps"));
        actionDisable_All_Maps->setCheckable(true);
        actionEnable_Auto_Maps = new QAction(MainWindow);
        actionEnable_Auto_Maps->setObjectName(QString::fromUtf8("actionEnable_Auto_Maps"));
        actionEnable_Auto_Maps->setCheckable(true);
        actionAuto_Map_Disable_Raster_Maps = new QAction(MainWindow);
        actionAuto_Map_Disable_Raster_Maps->setObjectName(QString::fromUtf8("actionAuto_Map_Disable_Raster_Maps"));
        actionAuto_Map_Disable_Raster_Maps->setCheckable(true);
        actionEnable_Map_Grid = new QAction(MainWindow);
        actionEnable_Map_Grid->setObjectName(QString::fromUtf8("actionEnable_Map_Grid"));
        actionEnable_Map_Grid->setCheckable(true);
        actionEnable_Map_Border = new QAction(MainWindow);
        actionEnable_Map_Border->setObjectName(QString::fromUtf8("actionEnable_Map_Border"));
        actionEnable_Map_Border->setCheckable(true);
        actionEnable_Map_Levels = new QAction(MainWindow);
        actionEnable_Map_Levels->setObjectName(QString::fromUtf8("actionEnable_Map_Levels"));
        actionEnable_Map_Levels->setCheckable(true);
        actionEnable_Map_Labels = new QAction(MainWindow);
        actionEnable_Map_Labels->setObjectName(QString::fromUtf8("actionEnable_Map_Labels"));
        actionEnable_Map_Labels->setCheckable(true);
        actionEnable_Area_Color_Fills = new QAction(MainWindow);
        actionEnable_Area_Color_Fills->setObjectName(QString::fromUtf8("actionEnable_Area_Color_Fills"));
        actionEnable_Area_Color_Fills->setCheckable(true);
        actionEnable_Weather_Alerts = new QAction(MainWindow);
        actionEnable_Weather_Alerts->setObjectName(QString::fromUtf8("actionEnable_Weather_Alerts"));
        actionEnable_Weather_Alerts->setCheckable(true);
        actionMouse_Pointer_Menu = new QAction(MainWindow);
        actionMouse_Pointer_Menu->setObjectName(QString::fromUtf8("actionMouse_Pointer_Menu"));
        action_Find_Stations = new QAction(MainWindow);
        action_Find_Stations->setObjectName(QString::fromUtf8("action_Find_Stations"));
        action_Track_Station = new QAction(MainWindow);
        action_Track_Station->setObjectName(QString::fromUtf8("action_Track_Station"));
        actionFetch_Find_u_Trail = new QAction(MainWindow);
        actionFetch_Find_u_Trail->setObjectName(QString::fromUtf8("actionFetch_Find_u_Trail"));
        action_Send_Message_To = new QAction(MainWindow);
        action_Send_Message_To->setObjectName(QString::fromUtf8("action_Send_Message_To"));
        actionShow_Pending_Messages = new QAction(MainWindow);
        actionShow_Pending_Messages->setObjectName(QString::fromUtf8("actionShow_Pending_Messages"));
        action_Open_Group_Messages = new QAction(MainWindow);
        action_Open_Group_Messages->setObjectName(QString::fromUtf8("action_Open_Group_Messages"));
        action_Clear_All_Outgoing_Messages = new QAction(MainWindow);
        action_Clear_All_Outgoing_Messages->setObjectName(QString::fromUtf8("action_Clear_All_Outgoing_Messages"));
        action_General_Stations_Query = new QAction(MainWindow);
        action_General_Stations_Query->setObjectName(QString::fromUtf8("action_General_Stations_Query"));
        action_IGate_Stations_Query = new QAction(MainWindow);
        action_IGate_Stations_Query->setObjectName(QString::fromUtf8("action_IGate_Stations_Query"));
        action_WX_Stations_Query = new QAction(MainWindow);
        action_WX_Stations_Query->setObjectName(QString::fromUtf8("action_WX_Stations_Query"));
        actionModify_Auto_Reply_Message = new QAction(MainWindow);
        actionModify_Auto_Reply_Message->setObjectName(QString::fromUtf8("actionModify_Auto_Reply_Message"));
        actionEnable_Auto_Reply_Message = new QAction(MainWindow);
        actionEnable_Auto_Reply_Message->setObjectName(QString::fromUtf8("actionEnable_Auto_Reply_Message"));
        actionEnable_Auto_Reply_Message->setCheckable(true);
        actionSatellite_Ack_Mode = new QAction(MainWindow);
        actionSatellite_Ack_Mode->setObjectName(QString::fromUtf8("actionSatellite_Ack_Mode"));
        actionSatellite_Ack_Mode->setCheckable(true);
        action_About = new QAction(MainWindow);
        action_About->setObjectName(QString::fromUtf8("action_About"));
        actionHelp_Index = new QAction(MainWindow);
        actionHelp_Index->setObjectName(QString::fromUtf8("actionHelp_Index"));
        actionInterface_Control = new QAction(MainWindow);
        actionInterface_Control->setObjectName(QString::fromUtf8("actionInterface_Control"));
        actionDisable_Transmit_ALL = new QAction(MainWindow);
        actionDisable_Transmit_ALL->setObjectName(QString::fromUtf8("actionDisable_Transmit_ALL"));
        actionDisable_Transmit_ALL->setCheckable(true);
        actionDisable_Transmit_My_Position = new QAction(MainWindow);
        actionDisable_Transmit_My_Position->setObjectName(QString::fromUtf8("actionDisable_Transmit_My_Position"));
        actionDisable_Transmit_My_Position->setCheckable(true);
        actionDisable_Transmit_Objects_Items = new QAction(MainWindow);
        actionDisable_Transmit_Objects_Items->setObjectName(QString::fromUtf8("actionDisable_Transmit_Objects_Items"));
        actionDisable_Transmit_Objects_Items->setCheckable(true);
        actionEnable_Server_Ports = new QAction(MainWindow);
        actionEnable_Server_Ports->setObjectName(QString::fromUtf8("actionEnable_Server_Ports"));
        actionEnable_Server_Ports->setCheckable(true);
        action_Transmit_Now = new QAction(MainWindow);
        action_Transmit_Now->setObjectName(QString::fromUtf8("action_Transmit_Now"));
        action_Fetch_GPS_Track = new QAction(MainWindow);
        action_Fetch_GPS_Track->setObjectName(QString::fromUtf8("action_Fetch_GPS_Track"));
        actionFetch_GPS_Routes = new QAction(MainWindow);
        actionFetch_GPS_Routes->setObjectName(QString::fromUtf8("actionFetch_GPS_Routes"));
        actionFetch_GPS_Waypoints = new QAction(MainWindow);
        actionFetch_GPS_Waypoints->setObjectName(QString::fromUtf8("actionFetch_GPS_Waypoints"));
        actionFetch_Garmin_RINO_Waypoints = new QAction(MainWindow);
        actionFetch_Garmin_RINO_Waypoints->setObjectName(QString::fromUtf8("actionFetch_Garmin_RINO_Waypoints"));
        action_EMERGENCY_BEACON_MODE = new QAction(MainWindow);
        action_EMERGENCY_BEACON_MODE->setObjectName(QString::fromUtf8("action_EMERGENCY_BEACON_MODE"));
        action_EMERGENCY_BEACON_MODE->setCheckable(true);
        action_Station = new QAction(MainWindow);
        action_Station->setObjectName(QString::fromUtf8("action_Station"));
        action_Defaults = new QAction(MainWindow);
        action_Defaults->setObjectName(QString::fromUtf8("action_Defaults"));
        action_Timing = new QAction(MainWindow);
        action_Timing->setObjectName(QString::fromUtf8("action_Timing"));
        actionC_oordinate_System = new QAction(MainWindow);
        actionC_oordinate_System->setObjectName(QString::fromUtf8("actionC_oordinate_System"));
        action_Audio_Alarms = new QAction(MainWindow);
        action_Audio_Alarms->setObjectName(QString::fromUtf8("action_Audio_Alarms"));
        actionS_peech = new QAction(MainWindow);
        actionS_peech->setObjectName(QString::fromUtf8("actionS_peech"));
        actionSmart_Beaconing = new QAction(MainWindow);
        actionSmart_Beaconing->setObjectName(QString::fromUtf8("actionSmart_Beaconing"));
        actionFonts = new QAction(MainWindow);
        actionFonts->setObjectName(QString::fromUtf8("actionFonts"));
        actionTest = new QAction(MainWindow);
        actionTest->setObjectName(QString::fromUtf8("actionTest"));
        actionChange_Debug_Level = new QAction(MainWindow);
        actionChange_Debug_Level->setObjectName(QString::fromUtf8("actionChange_Debug_Level"));
        actionEnable_English_Units = new QAction(MainWindow);
        actionEnable_English_Units->setObjectName(QString::fromUtf8("actionEnable_English_Units"));
        actionEnable_English_Units->setCheckable(true);
        actionDist_Bearing_Status = new QAction(MainWindow);
        actionDist_Bearing_Status->setObjectName(QString::fromUtf8("actionDist_Bearing_Status"));
        actionDist_Bearing_Status->setCheckable(true);
        actionSave_Config_Now = new QAction(MainWindow);
        actionSave_Config_Now->setObjectName(QString::fromUtf8("actionSave_Config_Now"));
        actionClose_Polygon = new QAction(MainWindow);
        actionClose_Polygon->setObjectName(QString::fromUtf8("actionClose_Polygon"));
        actionErase_CAD_Polygons = new QAction(MainWindow);
        actionErase_CAD_Polygons->setObjectName(QString::fromUtf8("actionErase_CAD_Polygons"));
        actionCAD_Polygons_2 = new QAction(MainWindow);
        actionCAD_Polygons_2->setObjectName(QString::fromUtf8("actionCAD_Polygons_2"));
        actionEnable_CAD_objects = new QAction(MainWindow);
        actionEnable_CAD_objects->setObjectName(QString::fromUtf8("actionEnable_CAD_objects"));
        actionEnable_CAD_objects->setCheckable(true);
        actionEnable_CAD_labels = new QAction(MainWindow);
        actionEnable_CAD_labels->setObjectName(QString::fromUtf8("actionEnable_CAD_labels"));
        actionEnable_CAD_labels->setCheckable(true);
        actionEnable_CAD_probability = new QAction(MainWindow);
        actionEnable_CAD_probability->setObjectName(QString::fromUtf8("actionEnable_CAD_probability"));
        actionEnable_CAD_probability->setCheckable(true);
        actionEnable_CAD_comments = new QAction(MainWindow);
        actionEnable_CAD_comments->setObjectName(QString::fromUtf8("actionEnable_CAD_comments"));
        actionEnable_CAD_comments->setCheckable(true);
        actionEnable_CAD_area_size = new QAction(MainWindow);
        actionEnable_CAD_area_size->setObjectName(QString::fromUtf8("actionEnable_CAD_area_size"));
        actionEnable_CAD_area_size->setCheckable(true);
        actionAdjust_Gamma_Correction = new QAction(MainWindow);
        actionAdjust_Gamma_Correction->setObjectName(QString::fromUtf8("actionAdjust_Gamma_Correction"));
        actionConfigure_Tigermap = new QAction(MainWindow);
        actionConfigure_Tigermap->setObjectName(QString::fromUtf8("actionConfigure_Tigermap"));
        actionConfigure_USGS_DRG = new QAction(MainWindow);
        actionConfigure_USGS_DRG->setObjectName(QString::fromUtf8("actionConfigure_USGS_DRG"));
        actionRe_download_Maps_Not_from_cache = new QAction(MainWindow);
        actionRe_download_Maps_Not_from_cache->setObjectName(QString::fromUtf8("actionRe_download_Maps_Not_from_cache"));
        actionFlush_Entire_Map_Cache = new QAction(MainWindow);
        actionFlush_Entire_Map_Cache->setObjectName(QString::fromUtf8("actionFlush_Entire_Map_Cache"));
        actionIndex_New_Maps_on_Startup = new QAction(MainWindow);
        actionIndex_New_Maps_on_Startup->setObjectName(QString::fromUtf8("actionIndex_New_Maps_on_Startup"));
        actionIndex_New_Maps_on_Startup->setCheckable(true);
        actionIndex_Add_New_Maps = new QAction(MainWindow);
        actionIndex_Add_New_Maps->setObjectName(QString::fromUtf8("actionIndex_Add_New_Maps"));
        actionIndex_Reindex_ALL_Maps = new QAction(MainWindow);
        actionIndex_Reindex_ALL_Maps->setObjectName(QString::fromUtf8("actionIndex_Reindex_ALL_Maps"));
        actionWhite = new QAction(MainWindow);
        actionWhite->setObjectName(QString::fromUtf8("actionWhite"));
        actionBlack = new QAction(MainWindow);
        actionBlack->setObjectName(QString::fromUtf8("actionBlack"));
        actionGray = new QAction(MainWindow);
        actionGray->setObjectName(QString::fromUtf8("actionGray"));
        actionMisty_Rose = new QAction(MainWindow);
        actionMisty_Rose->setObjectName(QString::fromUtf8("actionMisty_Rose"));
        actionNavy_Blue = new QAction(MainWindow);
        actionNavy_Blue->setObjectName(QString::fromUtf8("actionNavy_Blue"));
        actionSteel_Blue = new QAction(MainWindow);
        actionSteel_Blue->setObjectName(QString::fromUtf8("actionSteel_Blue"));
        actionMed_Sea_Green = new QAction(MainWindow);
        actionMed_Sea_Green->setObjectName(QString::fromUtf8("actionMed_Sea_Green"));
        actionPale_Green = new QAction(MainWindow);
        actionPale_Green->setObjectName(QString::fromUtf8("actionPale_Green"));
        actionPale_Goldenrod = new QAction(MainWindow);
        actionPale_Goldenrod->setObjectName(QString::fromUtf8("actionPale_Goldenrod"));
        actionGoldenrod_Yellow = new QAction(MainWindow);
        actionGoldenrod_Yellow->setObjectName(QString::fromUtf8("actionGoldenrod_Yellow"));
        actionRosy_Brown = new QAction(MainWindow);
        actionRosy_Brown->setObjectName(QString::fromUtf8("actionRosy_Brown"));
        actionFirebrick_Red = new QAction(MainWindow);
        actionFirebrick_Red->setObjectName(QString::fromUtf8("actionFirebrick_Red"));
        action0 = new QAction(MainWindow);
        action0->setObjectName(QString::fromUtf8("action0"));
        action10 = new QAction(MainWindow);
        action10->setObjectName(QString::fromUtf8("action10"));
        action20 = new QAction(MainWindow);
        action20->setObjectName(QString::fromUtf8("action20"));
        action30 = new QAction(MainWindow);
        action30->setObjectName(QString::fromUtf8("action30"));
        action40 = new QAction(MainWindow);
        action40->setObjectName(QString::fromUtf8("action40"));
        action50 = new QAction(MainWindow);
        action50->setObjectName(QString::fromUtf8("action50"));
        action60 = new QAction(MainWindow);
        action60->setObjectName(QString::fromUtf8("action60"));
        action70 = new QAction(MainWindow);
        action70->setObjectName(QString::fromUtf8("action70"));
        action80 = new QAction(MainWindow);
        action80->setObjectName(QString::fromUtf8("action80"));
        action90 = new QAction(MainWindow);
        action90->setObjectName(QString::fromUtf8("action90"));
        action100 = new QAction(MainWindow);
        action100->setObjectName(QString::fromUtf8("action100"));
        action_Black_Border = new QAction(MainWindow);
        action_Black_Border->setObjectName(QString::fromUtf8("action_Black_Border"));
        actionBlack_Shadow = new QAction(MainWindow);
        actionBlack_Shadow->setObjectName(QString::fromUtf8("actionBlack_Shadow"));
        action_Text_on_Black = new QAction(MainWindow);
        action_Text_on_Black->setObjectName(QString::fromUtf8("action_Text_on_Black"));
        action_No_Outline = new QAction(MainWindow);
        action_No_Outline->setObjectName(QString::fromUtf8("action_No_Outline"));
        action_Black_Outline = new QAction(MainWindow);
        action_Black_Outline->setObjectName(QString::fromUtf8("action_Black_Outline"));
        action_Grey_Outline = new QAction(MainWindow);
        action_Grey_Outline->setObjectName(QString::fromUtf8("action_Grey_Outline"));
        action_White_Outline = new QAction(MainWindow);
        action_White_Outline->setObjectName(QString::fromUtf8("action_White_Outline"));
        actionExport_to_KML_File = new QAction(MainWindow);
        actionExport_to_KML_File->setObjectName(QString::fromUtf8("actionExport_to_KML_File"));
        actionSelect_None = new QAction(MainWindow);
        actionSelect_None->setObjectName(QString::fromUtf8("actionSelect_None"));
        actionSelect_None->setCheckable(true);
        actionSelect_Mine = new QAction(MainWindow);
        actionSelect_Mine->setObjectName(QString::fromUtf8("actionSelect_Mine"));
        actionSelect_Mine->setCheckable(true);
        actionSelect_TNC = new QAction(MainWindow);
        actionSelect_TNC->setObjectName(QString::fromUtf8("actionSelect_TNC"));
        actionSelect_TNC->setCheckable(true);
        action_Select_Direct = new QAction(MainWindow);
        action_Select_Direct->setObjectName(QString::fromUtf8("action_Select_Direct"));
        action_Select_Direct->setCheckable(true);
        action_Select_Via_Digi = new QAction(MainWindow);
        action_Select_Via_Digi->setObjectName(QString::fromUtf8("action_Select_Via_Digi"));
        action_Select_Via_Digi->setCheckable(true);
        actionSelect_Net = new QAction(MainWindow);
        actionSelect_Net->setObjectName(QString::fromUtf8("actionSelect_Net"));
        actionSelect_Net->setCheckable(true);
        actionSelect_Tactical_Calls_Only = new QAction(MainWindow);
        actionSelect_Tactical_Calls_Only->setObjectName(QString::fromUtf8("actionSelect_Tactical_Calls_Only"));
        actionSelect_Tactical_Calls_Only->setCheckable(true);
        actionInclude_Expired_Data = new QAction(MainWindow);
        actionInclude_Expired_Data->setObjectName(QString::fromUtf8("actionInclude_Expired_Data"));
        actionInclude_Expired_Data->setCheckable(true);
        actionSelect_Stations = new QAction(MainWindow);
        actionSelect_Stations->setObjectName(QString::fromUtf8("actionSelect_Stations"));
        actionSelect_Stations->setCheckable(true);
        action_Select_Fixed_Stations = new QAction(MainWindow);
        action_Select_Fixed_Stations->setObjectName(QString::fromUtf8("action_Select_Fixed_Stations"));
        action_Select_Fixed_Stations->setCheckable(true);
        action_Select_Moving_Stations = new QAction(MainWindow);
        action_Select_Moving_Stations->setObjectName(QString::fromUtf8("action_Select_Moving_Stations"));
        action_Select_Moving_Stations->setCheckable(true);
        action_Select_WX_Stations = new QAction(MainWindow);
        action_Select_WX_Stations->setObjectName(QString::fromUtf8("action_Select_WX_Stations"));
        action_Select_WX_Stations->setCheckable(true);
        action_Select_CWOP_WX_Stations = new QAction(MainWindow);
        action_Select_CWOP_WX_Stations->setObjectName(QString::fromUtf8("action_Select_CWOP_WX_Stations"));
        action_Select_CWOP_WX_Stations->setCheckable(true);
        actionSelect_Objects_Items = new QAction(MainWindow);
        actionSelect_Objects_Items->setObjectName(QString::fromUtf8("actionSelect_Objects_Items"));
        actionSelect_Objects_Items->setCheckable(true);
        action_Select_WX_Objects_Items = new QAction(MainWindow);
        action_Select_WX_Objects_Items->setObjectName(QString::fromUtf8("action_Select_WX_Objects_Items"));
        action_Select_WX_Objects_Items->setCheckable(true);
        action_Select_Water_Gauge_Objects_Items = new QAction(MainWindow);
        action_Select_Water_Gauge_Objects_Items->setObjectName(QString::fromUtf8("action_Select_Water_Gauge_Objects_Items"));
        action_Select_Water_Gauge_Objects_Items->setCheckable(true);
        action_Select_Other_Objects_Items = new QAction(MainWindow);
        action_Select_Other_Objects_Items->setObjectName(QString::fromUtf8("action_Select_Other_Objects_Items"));
        action_Select_Other_Objects_Items->setCheckable(true);
        actionDisplay_Callsign = new QAction(MainWindow);
        actionDisplay_Callsign->setObjectName(QString::fromUtf8("actionDisplay_Callsign"));
        actionDisplay_Callsign->setCheckable(true);
        action_Label_Trailpoints = new QAction(MainWindow);
        action_Label_Trailpoints->setObjectName(QString::fromUtf8("action_Label_Trailpoints"));
        action_Label_Trailpoints->setCheckable(true);
        actionDisplay_Symbol = new QAction(MainWindow);
        actionDisplay_Symbol->setObjectName(QString::fromUtf8("actionDisplay_Symbol"));
        actionDisplay_Symbol->setCheckable(true);
        action_Rotate_Symbol = new QAction(MainWindow);
        action_Rotate_Symbol->setObjectName(QString::fromUtf8("action_Rotate_Symbol"));
        action_Rotate_Symbol->setCheckable(true);
        actionDisplay_Trail = new QAction(MainWindow);
        actionDisplay_Trail->setObjectName(QString::fromUtf8("actionDisplay_Trail"));
        actionDisplay_Trail->setCheckable(true);
        actionDisplay_Course = new QAction(MainWindow);
        actionDisplay_Course->setObjectName(QString::fromUtf8("actionDisplay_Course"));
        actionDisplay_Course->setCheckable(true);
        actionDisplay_Speed = new QAction(MainWindow);
        actionDisplay_Speed->setObjectName(QString::fromUtf8("actionDisplay_Speed"));
        actionDisplay_Speed->setCheckable(true);
        action_Display_Short_Speed = new QAction(MainWindow);
        action_Display_Short_Speed->setObjectName(QString::fromUtf8("action_Display_Short_Speed"));
        action_Display_Short_Speed->setCheckable(true);
        actionDisplay_Altitude = new QAction(MainWindow);
        actionDisplay_Altitude->setObjectName(QString::fromUtf8("actionDisplay_Altitude"));
        actionDisplay_Altitude->setCheckable(true);
        actionDisplay_Weather_Info = new QAction(MainWindow);
        actionDisplay_Weather_Info->setObjectName(QString::fromUtf8("actionDisplay_Weather_Info"));
        actionDisplay_Weather_Info->setCheckable(true);
        action_Display_Weather_Text = new QAction(MainWindow);
        action_Display_Weather_Text->setObjectName(QString::fromUtf8("action_Display_Weather_Text"));
        action_Display_Weather_Text->setCheckable(true);
        action_Temperature_Only = new QAction(MainWindow);
        action_Temperature_Only->setObjectName(QString::fromUtf8("action_Temperature_Only"));
        action_Temperature_Only->setCheckable(true);
        action_Display_Wind_Barb = new QAction(MainWindow);
        action_Display_Wind_Barb->setObjectName(QString::fromUtf8("action_Display_Wind_Barb"));
        action_Display_Wind_Barb->setCheckable(true);
        actionDisplay_Aloha_Circle = new QAction(MainWindow);
        actionDisplay_Aloha_Circle->setObjectName(QString::fromUtf8("actionDisplay_Aloha_Circle"));
        actionDisplay_Aloha_Circle->setCheckable(true);
        actionDisplay_Position_Ambiguity = new QAction(MainWindow);
        actionDisplay_Position_Ambiguity->setObjectName(QString::fromUtf8("actionDisplay_Position_Ambiguity"));
        actionDisplay_Position_Ambiguity->setCheckable(true);
        actionDisplay_Power_Gain = new QAction(MainWindow);
        actionDisplay_Power_Gain->setObjectName(QString::fromUtf8("actionDisplay_Power_Gain"));
        actionDisplay_Power_Gain->setCheckable(true);
        action_Use_Default_Power_Gain = new QAction(MainWindow);
        action_Use_Default_Power_Gain->setObjectName(QString::fromUtf8("action_Use_Default_Power_Gain"));
        action_Use_Default_Power_Gain->setCheckable(true);
        action_Display_Mobile_Power_Gain = new QAction(MainWindow);
        action_Display_Mobile_Power_Gain->setObjectName(QString::fromUtf8("action_Display_Mobile_Power_Gain"));
        action_Display_Mobile_Power_Gain->setCheckable(true);
        actionDisplay_DF_Attributes = new QAction(MainWindow);
        actionDisplay_DF_Attributes->setObjectName(QString::fromUtf8("actionDisplay_DF_Attributes"));
        actionDisplay_DF_Attributes->setCheckable(true);
        actionDisplay_DF_Beamwidth = new QAction(MainWindow);
        actionDisplay_DF_Beamwidth->setObjectName(QString::fromUtf8("actionDisplay_DF_Beamwidth"));
        actionDisplay_DF_Beamwidth->setCheckable(true);
        actionDisplay_DF_Bearing = new QAction(MainWindow);
        actionDisplay_DF_Bearing->setObjectName(QString::fromUtf8("actionDisplay_DF_Bearing"));
        actionDisplay_DF_Bearing->setCheckable(true);
        actionEnable_Dead_Reckoning = new QAction(MainWindow);
        actionEnable_Dead_Reckoning->setObjectName(QString::fromUtf8("actionEnable_Dead_Reckoning"));
        actionEnable_Dead_Reckoning->setCheckable(true);
        action_Display_Arc = new QAction(MainWindow);
        action_Display_Arc->setObjectName(QString::fromUtf8("action_Display_Arc"));
        action_Display_Arc->setCheckable(true);
        action_Display_Course = new QAction(MainWindow);
        action_Display_Course->setObjectName(QString::fromUtf8("action_Display_Course"));
        action_Display_Course->setCheckable(true);
        action_Display_Symbol = new QAction(MainWindow);
        action_Display_Symbol->setObjectName(QString::fromUtf8("action_Display_Symbol"));
        action_Display_Symbol->setCheckable(true);
        actionDIsplay_Dist_Bearing = new QAction(MainWindow);
        actionDIsplay_Dist_Bearing->setObjectName(QString::fromUtf8("actionDIsplay_Dist_Bearing"));
        actionDIsplay_Dist_Bearing->setCheckable(true);
        actionDisplay_Last_Report_Age = new QAction(MainWindow);
        actionDisplay_Last_Report_Age->setObjectName(QString::fromUtf8("actionDisplay_Last_Report_Age"));
        actionDisplay_Last_Report_Age->setCheckable(true);
        actionReload_Object_Item_History = new QAction(MainWindow);
        actionReload_Object_Item_History->setObjectName(QString::fromUtf8("actionReload_Object_Item_History"));
        actionClear_Object_Item_History = new QAction(MainWindow);
        actionClear_Object_Item_History->setObjectName(QString::fromUtf8("actionClear_Object_Item_History"));
        actionClear_All_Tactical_Calls = new QAction(MainWindow);
        actionClear_All_Tactical_Calls->setObjectName(QString::fromUtf8("actionClear_All_Tactical_Calls"));
        actionClear_Tactical_Call_History = new QAction(MainWindow);
        actionClear_Tactical_Call_History->setObjectName(QString::fromUtf8("actionClear_Tactical_Call_History"));
        action_Clear_All_Trails = new QAction(MainWindow);
        action_Clear_All_Trails->setObjectName(QString::fromUtf8("action_Clear_All_Trails"));
        actionClear_All_Stations = new QAction(MainWindow);
        actionClear_All_Stations->setObjectName(QString::fromUtf8("actionClear_All_Stations"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        horizontalLayout = new QHBoxLayout(centralWidget);
        horizontalLayout->setSpacing(6);
        horizontalLayout->setContentsMargins(0, 0, 0, 0);
        horizontalLayout->setObjectName(QString::fromUtf8("horizontalLayout"));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setTabPosition(QTabWidget::West);
        tabWidget->setTabShape(QTabWidget::Triangular);
        Map1 = new QWidget();
        Map1->setObjectName(QString::fromUtf8("Map1"));
        verticalLayout = new QVBoxLayout(Map1);
        verticalLayout->setSpacing(6);
        verticalLayout->setContentsMargins(11, 11, 11, 11);
        verticalLayout->setObjectName(QString::fromUtf8("verticalLayout"));
        incomingPackets = new QLabel(Map1);
        incomingPackets->setObjectName(QString::fromUtf8("incomingPackets"));
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(incomingPackets->sizePolicy().hasHeightForWidth());
        incomingPackets->setSizePolicy(sizePolicy);
        incomingPackets->setMinimumSize(QSize(100, 30));
        incomingPackets->setBaseSize(QSize(100, 30));
        incomingPackets->setTextFormat(Qt::PlainText);
        incomingPackets->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);

        verticalLayout->addWidget(incomingPackets);

        tabWidget->addTab(Map1, QString());
        Map2 = new QWidget();
        Map2->setObjectName(QString::fromUtf8("Map2"));
        toolButton = new QToolButton(Map2);
        toolButton->setObjectName(QString::fromUtf8("toolButton"));
        toolButton->setGeometry(QRect(10, 60, 25, 24));
        tabWidget->addTab(Map2, QString());
        Map3 = new QWidget();
        Map3->setObjectName(QString::fromUtf8("Map3"));
        checkBox = new QCheckBox(Map3);
        checkBox->setObjectName(QString::fromUtf8("checkBox"));
        checkBox->setGeometry(QRect(20, 120, 79, 20));
        tabWidget->addTab(Map3, QString());
        Map4 = new QWidget();
        Map4->setObjectName(QString::fromUtf8("Map4"));
        buttonBox = new QDialogButtonBox(Map4);
        buttonBox->setObjectName(QString::fromUtf8("buttonBox"));
        buttonBox->setGeometry(QRect(10, 170, 160, 26));
        buttonBox->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::Ok);
        tabWidget->addTab(Map4, QString());

        horizontalLayout->addWidget(tabWidget);

        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1036, 22));
        menuBar->setMaximumSize(QSize(16777215, 16777215));
        menuBar->setAutoFillBackground(false);
        menuFile = new QMenu(menuBar);
        menuFile->setObjectName(QString::fromUtf8("menuFile"));
        menuFile->setTearOffEnabled(true);
        menu_Configure = new QMenu(menuFile);
        menu_Configure->setObjectName(QString::fromUtf8("menu_Configure"));
        menu_Configure->setTearOffEnabled(true);
        menuView = new QMenu(menuBar);
        menuView->setObjectName(QString::fromUtf8("menuView"));
        menuView->setTearOffEnabled(true);
        menuMap = new QMenu(menuBar);
        menuMap->setObjectName(QString::fromUtf8("menuMap"));
        menuMap->setTearOffEnabled(true);
        menuDraw_CAD_Objects = new QMenu(menuMap);
        menuDraw_CAD_Objects->setObjectName(QString::fromUtf8("menuDraw_CAD_Objects"));
        menuDraw_CAD_Objects->setTearOffEnabled(true);
        menuConfigure = new QMenu(menuMap);
        menuConfigure->setObjectName(QString::fromUtf8("menuConfigure"));
        menuConfigure->setTearOffEnabled(true);
        menuBackground_Color = new QMenu(menuConfigure);
        menuBackground_Color->setObjectName(QString::fromUtf8("menuBackground_Color"));
        menuBackground_Color->setTearOffEnabled(true);
        menuMap_Intensity = new QMenu(menuConfigure);
        menuMap_Intensity->setObjectName(QString::fromUtf8("menuMap_Intensity"));
        menuMap_Intensity->setTearOffEnabled(true);
        menuStation_Text_Style = new QMenu(menuConfigure);
        menuStation_Text_Style->setObjectName(QString::fromUtf8("menuStation_Text_Style"));
        menuStation_Text_Style->setTearOffEnabled(true);
        menuIcon_Outline_Style = new QMenu(menuConfigure);
        menuIcon_Outline_Style->setObjectName(QString::fromUtf8("menuIcon_Outline_Style"));
        menuIcon_Outline_Style->setTearOffEnabled(true);
        menuStation = new QMenu(menuBar);
        menuStation->setObjectName(QString::fromUtf8("menuStation"));
        menuStation->setTearOffEnabled(true);
        menu_Export_All = new QMenu(menuStation);
        menu_Export_All->setObjectName(QString::fromUtf8("menu_Export_All"));
        menu_Export_All->setTearOffEnabled(true);
        menuFilter_Data = new QMenu(menuStation);
        menuFilter_Data->setObjectName(QString::fromUtf8("menuFilter_Data"));
        menuFilter_Data->setTearOffEnabled(true);
        menuFilter_Display = new QMenu(menuStation);
        menuFilter_Display->setObjectName(QString::fromUtf8("menuFilter_Display"));
        menuFilter_Display->setTearOffEnabled(true);
        menuConfigure_2 = new QMenu(menuStation);
        menuConfigure_2->setObjectName(QString::fromUtf8("menuConfigure_2"));
        menuConfigure_2->setTearOffEnabled(true);
        menuMessage = new QMenu(menuBar);
        menuMessage->setObjectName(QString::fromUtf8("menuMessage"));
        menuMessage->setTearOffEnabled(true);
        menuInterface = new QMenu(menuBar);
        menuInterface->setObjectName(QString::fromUtf8("menuInterface"));
        menuInterface->setTearOffEnabled(true);
        menuHelp = new QMenu(menuBar);
        menuHelp->setObjectName(QString::fromUtf8("menuHelp"));
        menuHelp->setTearOffEnabled(true);
        menu_EMERGENCY_BEACON_MODE_ENABLE = new QMenu(menuHelp);
        menu_EMERGENCY_BEACON_MODE_ENABLE->setObjectName(QString::fromUtf8("menu_EMERGENCY_BEACON_MODE_ENABLE"));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        menuBar->addAction(menuFile->menuAction());
        menuBar->addAction(menuView->menuAction());
        menuBar->addAction(menuMap->menuAction());
        menuBar->addAction(menuStation->menuAction());
        menuBar->addAction(menuMessage->menuAction());
        menuBar->addAction(menuInterface->menuAction());
        menuBar->addAction(menuHelp->menuAction());
        menuFile->addAction(actionPrint);
        menuFile->addAction(menu_Configure->menuAction());
        menuFile->addSeparator();
        menuFile->addAction(actionOpen_Log_File);
        menuFile->addAction(actionTNC_Logging);
        menuFile->addAction(actionNet_Logging);
        menuFile->addAction(actionIGate_Logging);
        menuFile->addAction(actionMessage_Logging);
        menuFile->addAction(actionWX_Logging);
        menuFile->addAction(actionWX_Alert_Logging);
        menuFile->addAction(actionPNG_Snapshots);
        menuFile->addAction(actionKML_Snapshots);
        menuFile->addSeparator();
        menuFile->addAction(actionE_xit);
        menu_Configure->addAction(action_Station);
        menu_Configure->addAction(action_Defaults);
        menu_Configure->addAction(action_Timing);
        menu_Configure->addAction(actionC_oordinate_System);
        menu_Configure->addAction(action_Audio_Alarms);
        menu_Configure->addAction(actionS_peech);
        menu_Configure->addAction(actionSmart_Beaconing);
        menu_Configure->addAction(actionFonts);
        menu_Configure->addAction(actionTest);
        menu_Configure->addAction(actionChange_Debug_Level);
        menu_Configure->addAction(actionEnable_English_Units);
        menu_Configure->addAction(actionDist_Bearing_Status);
        menu_Configure->addSeparator();
        menu_Configure->addAction(actionSave_Config_Now);
        menuView->addAction(action_Incoming_Data);
        menuView->addAction(actionMessage_Traffic);
        menuView->addAction(action_Bulletins);
        menuView->addSeparator();
        menuView->addAction(action_Mobile_Stations);
        menuView->addAction(action_All_Stations);
        menuView->addAction(actionLocal_Stations);
        menuView->addAction(action_Last_Stations);
        menuView->addSeparator();
        menuView->addAction(actionObjects_Items);
        menuView->addAction(actionOwn_Objects_Items);
        menuView->addAction(actionCAD_Polygons);
        menuView->addSeparator();
        menuView->addAction(action_Weather_Stations);
        menuView->addAction(actionOwn_Weather_Data);
        menuView->addAction(actionW_eather_Alerts);
        menuView->addSeparator();
        menuView->addAction(actionGPS_Status);
        menuView->addAction(action_Uptime);
        menuView->addAction(actionALOHA_Statistics);
        menuMap->addAction(action_Map_Chooser);
        menuMap->addAction(actionMap_Display_Bookmarks);
        menuMap->addAction(actionLocate_Map_Feature);
        menuMap->addAction(actionFind_Address);
        menuMap->addAction(actionCoordinate_Calculator);
        menuMap->addAction(actionCenter_Zoom);
        menuMap->addAction(menuDraw_CAD_Objects->menuAction());
        menuMap->addSeparator();
        menuMap->addAction(actionDisable_Fast_Zoom_Pan_Home);
        menuMap->addAction(actionDisable_All_Maps);
        menuMap->addAction(actionEnable_Auto_Maps);
        menuMap->addAction(actionAuto_Map_Disable_Raster_Maps);
        menuMap->addAction(actionEnable_Map_Grid);
        menuMap->addAction(actionEnable_Map_Border);
        menuMap->addAction(actionEnable_Map_Levels);
        menuMap->addAction(actionEnable_Map_Labels);
        menuMap->addAction(actionEnable_Area_Color_Fills);
        menuMap->addAction(actionEnable_Weather_Alerts);
        menuMap->addSeparator();
        menuMap->addAction(menuConfigure->menuAction());
        menuMap->addSeparator();
        menuMap->addAction(actionMouse_Pointer_Menu);
        menuDraw_CAD_Objects->addAction(actionClose_Polygon);
        menuDraw_CAD_Objects->addAction(actionErase_CAD_Polygons);
        menuDraw_CAD_Objects->addAction(actionCAD_Polygons_2);
        menuDraw_CAD_Objects->addAction(actionEnable_CAD_objects);
        menuDraw_CAD_Objects->addAction(actionEnable_CAD_labels);
        menuDraw_CAD_Objects->addAction(actionEnable_CAD_probability);
        menuDraw_CAD_Objects->addAction(actionEnable_CAD_comments);
        menuDraw_CAD_Objects->addAction(actionEnable_CAD_area_size);
        menuConfigure->addAction(menuBackground_Color->menuAction());
        menuConfigure->addAction(menuMap_Intensity->menuAction());
        menuConfigure->addAction(actionAdjust_Gamma_Correction);
        menuConfigure->addAction(menuStation_Text_Style->menuAction());
        menuConfigure->addAction(menuIcon_Outline_Style->menuAction());
        menuConfigure->addAction(actionConfigure_Tigermap);
        menuConfigure->addAction(actionConfigure_USGS_DRG);
        menuConfigure->addSeparator();
        menuConfigure->addAction(actionRe_download_Maps_Not_from_cache);
        menuConfigure->addAction(actionFlush_Entire_Map_Cache);
        menuConfigure->addAction(actionIndex_New_Maps_on_Startup);
        menuConfigure->addAction(actionIndex_Add_New_Maps);
        menuConfigure->addAction(actionIndex_Reindex_ALL_Maps);
        menuBackground_Color->addAction(actionWhite);
        menuBackground_Color->addAction(actionBlack);
        menuBackground_Color->addAction(actionGray);
        menuBackground_Color->addAction(actionMisty_Rose);
        menuBackground_Color->addAction(actionNavy_Blue);
        menuBackground_Color->addAction(actionSteel_Blue);
        menuBackground_Color->addAction(actionMed_Sea_Green);
        menuBackground_Color->addAction(actionPale_Green);
        menuBackground_Color->addAction(actionPale_Goldenrod);
        menuBackground_Color->addAction(actionGoldenrod_Yellow);
        menuBackground_Color->addAction(actionRosy_Brown);
        menuBackground_Color->addAction(actionFirebrick_Red);
        menuMap_Intensity->addAction(action0);
        menuMap_Intensity->addAction(action10);
        menuMap_Intensity->addAction(action20);
        menuMap_Intensity->addAction(action30);
        menuMap_Intensity->addAction(action40);
        menuMap_Intensity->addAction(action50);
        menuMap_Intensity->addAction(action60);
        menuMap_Intensity->addAction(action70);
        menuMap_Intensity->addAction(action80);
        menuMap_Intensity->addAction(action90);
        menuMap_Intensity->addAction(action100);
        menuStation_Text_Style->addAction(action_Black_Border);
        menuStation_Text_Style->addAction(actionBlack_Shadow);
        menuStation_Text_Style->addAction(action_Text_on_Black);
        menuIcon_Outline_Style->addAction(action_No_Outline);
        menuIcon_Outline_Style->addAction(action_Black_Outline);
        menuIcon_Outline_Style->addAction(action_Grey_Outline);
        menuIcon_Outline_Style->addAction(action_White_Outline);
        menuStation->addAction(action_Find_Stations);
        menuStation->addAction(action_Track_Station);
        menuStation->addAction(actionFetch_Find_u_Trail);
        menuStation->addAction(menu_Export_All->menuAction());
        menuStation->addSeparator();
        menuStation->addAction(menuFilter_Data->menuAction());
        menuStation->addAction(menuFilter_Display->menuAction());
        menuStation->addSeparator();
        menuStation->addAction(menuConfigure_2->menuAction());
        menu_Export_All->addAction(actionExport_to_KML_File);
        menuFilter_Data->addAction(actionSelect_None);
        menuFilter_Data->addAction(actionSelect_Mine);
        menuFilter_Data->addAction(actionSelect_TNC);
        menuFilter_Data->addAction(action_Select_Direct);
        menuFilter_Data->addAction(action_Select_Via_Digi);
        menuFilter_Data->addAction(actionSelect_Net);
        menuFilter_Data->addAction(actionSelect_Tactical_Calls_Only);
        menuFilter_Data->addAction(actionInclude_Expired_Data);
        menuFilter_Data->addSeparator();
        menuFilter_Data->addAction(actionSelect_Stations);
        menuFilter_Data->addAction(action_Select_Fixed_Stations);
        menuFilter_Data->addAction(action_Select_Moving_Stations);
        menuFilter_Data->addAction(action_Select_WX_Stations);
        menuFilter_Data->addAction(action_Select_CWOP_WX_Stations);
        menuFilter_Data->addAction(actionSelect_Objects_Items);
        menuFilter_Data->addAction(action_Select_WX_Objects_Items);
        menuFilter_Data->addAction(action_Select_Water_Gauge_Objects_Items);
        menuFilter_Data->addAction(action_Select_Other_Objects_Items);
        menuFilter_Display->addAction(actionDisplay_Callsign);
        menuFilter_Display->addAction(action_Label_Trailpoints);
        menuFilter_Display->addAction(actionDisplay_Symbol);
        menuFilter_Display->addAction(action_Rotate_Symbol);
        menuFilter_Display->addAction(actionDisplay_Trail);
        menuFilter_Display->addSeparator();
        menuFilter_Display->addAction(actionDisplay_Course);
        menuFilter_Display->addAction(actionDisplay_Speed);
        menuFilter_Display->addAction(action_Display_Short_Speed);
        menuFilter_Display->addAction(actionDisplay_Altitude);
        menuFilter_Display->addSeparator();
        menuFilter_Display->addAction(actionDisplay_Weather_Info);
        menuFilter_Display->addAction(action_Display_Weather_Text);
        menuFilter_Display->addAction(action_Temperature_Only);
        menuFilter_Display->addAction(action_Display_Wind_Barb);
        menuFilter_Display->addSeparator();
        menuFilter_Display->addAction(actionDisplay_Aloha_Circle);
        menuFilter_Display->addAction(actionDisplay_Position_Ambiguity);
        menuFilter_Display->addAction(actionDisplay_Power_Gain);
        menuFilter_Display->addAction(action_Use_Default_Power_Gain);
        menuFilter_Display->addAction(action_Display_Mobile_Power_Gain);
        menuFilter_Display->addSeparator();
        menuFilter_Display->addAction(actionDisplay_DF_Attributes);
        menuFilter_Display->addAction(actionDisplay_DF_Beamwidth);
        menuFilter_Display->addAction(actionDisplay_DF_Bearing);
        menuFilter_Display->addSeparator();
        menuFilter_Display->addAction(actionEnable_Dead_Reckoning);
        menuFilter_Display->addAction(action_Display_Arc);
        menuFilter_Display->addAction(action_Display_Course);
        menuFilter_Display->addAction(action_Display_Symbol);
        menuFilter_Display->addSeparator();
        menuFilter_Display->addAction(actionDIsplay_Dist_Bearing);
        menuFilter_Display->addAction(actionDisplay_Last_Report_Age);
        menuConfigure_2->addAction(actionReload_Object_Item_History);
        menuConfigure_2->addAction(actionClear_Object_Item_History);
        menuConfigure_2->addAction(actionClear_All_Tactical_Calls);
        menuConfigure_2->addAction(actionClear_Tactical_Call_History);
        menuConfigure_2->addAction(action_Clear_All_Trails);
        menuConfigure_2->addAction(actionClear_All_Stations);
        menuMessage->addAction(action_Send_Message_To);
        menuMessage->addAction(actionShow_Pending_Messages);
        menuMessage->addAction(action_Open_Group_Messages);
        menuMessage->addAction(action_Clear_All_Outgoing_Messages);
        menuMessage->addSeparator();
        menuMessage->addAction(action_General_Stations_Query);
        menuMessage->addAction(action_IGate_Stations_Query);
        menuMessage->addAction(action_WX_Stations_Query);
        menuMessage->addSeparator();
        menuMessage->addAction(actionModify_Auto_Reply_Message);
        menuMessage->addAction(actionEnable_Auto_Reply_Message);
        menuMessage->addSeparator();
        menuMessage->addAction(actionSatellite_Ack_Mode);
        menuInterface->addAction(actionInterface_Control);
        menuInterface->addSeparator();
        menuInterface->addAction(actionDisable_Transmit_ALL);
        menuInterface->addAction(actionDisable_Transmit_My_Position);
        menuInterface->addAction(actionDisable_Transmit_Objects_Items);
        menuInterface->addAction(actionEnable_Server_Ports);
        menuInterface->addSeparator();
        menuInterface->addAction(action_Transmit_Now);
        menuInterface->addAction(action_Fetch_GPS_Track);
        menuInterface->addAction(actionFetch_GPS_Routes);
        menuInterface->addAction(actionFetch_GPS_Waypoints);
        menuInterface->addAction(actionFetch_Garmin_RINO_Waypoints);
        menuHelp->addAction(action_About);
        menuHelp->addAction(actionHelp_Index);
        menuHelp->addSeparator();
        menuHelp->addAction(menu_EMERGENCY_BEACON_MODE_ENABLE->menuAction());
        menu_EMERGENCY_BEACON_MODE_ENABLE->addAction(action_EMERGENCY_BEACON_MODE);

        retranslateUi(MainWindow);
        QObject::connect(actionE_xit, SIGNAL(triggered()), MainWindow, SLOT(close()));
        QObject::connect(actionInterface_Control, SIGNAL(triggered()), MainWindow, SLOT(interfaceControlAction()));
        QObject::connect(action_Station, SIGNAL(triggered()), MainWindow, SLOT(stationSettingsAction()));

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0, QApplication::UnicodeUTF8));
        actionPrint->setText(QApplication::translate("MainWindow", "&Print", 0, QApplication::UnicodeUTF8));
        actionOpen_Log_File->setText(QApplication::translate("MainWindow", "&Open Log File", 0, QApplication::UnicodeUTF8));
        actionTNC_Logging->setText(QApplication::translate("MainWindow", "&TNC Logging", 0, QApplication::UnicodeUTF8));
        actionNet_Logging->setText(QApplication::translate("MainWindow", "&Net Logging", 0, QApplication::UnicodeUTF8));
        actionIGate_Logging->setText(QApplication::translate("MainWindow", "&IGate Logging", 0, QApplication::UnicodeUTF8));
        actionMessage_Logging->setText(QApplication::translate("MainWindow", "&Message Logging", 0, QApplication::UnicodeUTF8));
        actionWX_Logging->setText(QApplication::translate("MainWindow", "&WX Logging", 0, QApplication::UnicodeUTF8));
        actionWX_Alert_Logging->setText(QApplication::translate("MainWindow", "WX &Alert Logging", 0, QApplication::UnicodeUTF8));
        actionPNG_Snapshots->setText(QApplication::translate("MainWindow", "PNG &Snapshots", 0, QApplication::UnicodeUTF8));
        actionKML_Snapshots->setText(QApplication::translate("MainWindow", "&KML Snapshots", 0, QApplication::UnicodeUTF8));
        actionE_xit->setText(QApplication::translate("MainWindow", "E&xit", 0, QApplication::UnicodeUTF8));
        action_Incoming_Data->setText(QApplication::translate("MainWindow", "&Incoming Data", 0, QApplication::UnicodeUTF8));
        actionMessage_Traffic->setText(QApplication::translate("MainWindow", "Message &Traffic", 0, QApplication::UnicodeUTF8));
        action_Bulletins->setText(QApplication::translate("MainWindow", "&Bulletins", 0, QApplication::UnicodeUTF8));
        action_Mobile_Stations->setText(QApplication::translate("MainWindow", "&Mobile Stations", 0, QApplication::UnicodeUTF8));
        action_All_Stations->setText(QApplication::translate("MainWindow", "&All Stations", 0, QApplication::UnicodeUTF8));
        actionLocal_Stations->setText(QApplication::translate("MainWindow", "Local &Stations", 0, QApplication::UnicodeUTF8));
        action_Last_Stations->setText(QApplication::translate("MainWindow", "&Last Stations", 0, QApplication::UnicodeUTF8));
        actionObjects_Items->setText(QApplication::translate("MainWindow", "Objects && Items", 0, QApplication::UnicodeUTF8));
        actionOwn_Objects_Items->setText(QApplication::translate("MainWindow", "Own Objects && Items", 0, QApplication::UnicodeUTF8));
        actionCAD_Polygons->setText(QApplication::translate("MainWindow", "CAD Polygons", 0, QApplication::UnicodeUTF8));
        action_Weather_Stations->setText(QApplication::translate("MainWindow", "&Weather Stations", 0, QApplication::UnicodeUTF8));
        actionOwn_Weather_Data->setText(QApplication::translate("MainWindow", "Own Weather &Data", 0, QApplication::UnicodeUTF8));
        actionW_eather_Alerts->setText(QApplication::translate("MainWindow", "W&eather Alerts", 0, QApplication::UnicodeUTF8));
        actionGPS_Status->setText(QApplication::translate("MainWindow", "GPS Status", 0, QApplication::UnicodeUTF8));
        action_Uptime->setText(QApplication::translate("MainWindow", "&Uptime", 0, QApplication::UnicodeUTF8));
        actionALOHA_Statistics->setText(QApplication::translate("MainWindow", "ALOHA Statistics", 0, QApplication::UnicodeUTF8));
        action_Map_Chooser->setText(QApplication::translate("MainWindow", "&Map Chooser", 0, QApplication::UnicodeUTF8));
        actionMap_Display_Bookmarks->setText(QApplication::translate("MainWindow", "Map Display &Bookmarks", 0, QApplication::UnicodeUTF8));
        actionLocate_Map_Feature->setText(QApplication::translate("MainWindow", "Locate Map &Feature", 0, QApplication::UnicodeUTF8));
        actionFind_Address->setText(QApplication::translate("MainWindow", "Find Address", 0, QApplication::UnicodeUTF8));
        actionCoordinate_Calculator->setText(QApplication::translate("MainWindow", "Coordinate Calculator", 0, QApplication::UnicodeUTF8));
        actionCenter_Zoom->setText(QApplication::translate("MainWindow", "Center && Zoom", 0, QApplication::UnicodeUTF8));
        actionDisable_Fast_Zoom_Pan_Home->setText(QApplication::translate("MainWindow", "Disable Fast Zoom/Pan/Home", 0, QApplication::UnicodeUTF8));
        actionDisable_All_Maps->setText(QApplication::translate("MainWindow", "Disable All Maps", 0, QApplication::UnicodeUTF8));
        actionEnable_Auto_Maps->setText(QApplication::translate("MainWindow", "Enable Auto Maps", 0, QApplication::UnicodeUTF8));
        actionAuto_Map_Disable_Raster_Maps->setText(QApplication::translate("MainWindow", "- Disable Raster Maps", 0, QApplication::UnicodeUTF8));
        actionEnable_Map_Grid->setText(QApplication::translate("MainWindow", "Enable Map Grid", 0, QApplication::UnicodeUTF8));
        actionEnable_Map_Border->setText(QApplication::translate("MainWindow", "Enable Map Border", 0, QApplication::UnicodeUTF8));
        actionEnable_Map_Levels->setText(QApplication::translate("MainWindow", "Enable Map Levels", 0, QApplication::UnicodeUTF8));
        actionEnable_Map_Labels->setText(QApplication::translate("MainWindow", "Enable Map Labels", 0, QApplication::UnicodeUTF8));
        actionEnable_Area_Color_Fills->setText(QApplication::translate("MainWindow", "Enable Area Color Fills", 0, QApplication::UnicodeUTF8));
        actionEnable_Weather_Alerts->setText(QApplication::translate("MainWindow", "Enable Weather Alerts", 0, QApplication::UnicodeUTF8));
        actionMouse_Pointer_Menu->setText(QApplication::translate("MainWindow", "Mouse Pointer Menu", 0, QApplication::UnicodeUTF8));
        action_Find_Stations->setText(QApplication::translate("MainWindow", "&Find Station", 0, QApplication::UnicodeUTF8));
        action_Track_Station->setText(QApplication::translate("MainWindow", "&Track Station", 0, QApplication::UnicodeUTF8));
        actionFetch_Find_u_Trail->setText(QApplication::translate("MainWindow", "Fetch Find&u Trail", 0, QApplication::UnicodeUTF8));
        action_Send_Message_To->setText(QApplication::translate("MainWindow", "&Send Message To", 0, QApplication::UnicodeUTF8));
        actionShow_Pending_Messages->setText(QApplication::translate("MainWindow", "Show &Pending Messages", 0, QApplication::UnicodeUTF8));
        action_Open_Group_Messages->setText(QApplication::translate("MainWindow", "&Open Group Messages", 0, QApplication::UnicodeUTF8));
        action_Clear_All_Outgoing_Messages->setText(QApplication::translate("MainWindow", "&Clear All Outgoing Messages", 0, QApplication::UnicodeUTF8));
        action_General_Stations_Query->setText(QApplication::translate("MainWindow", "&General Stations Query", 0, QApplication::UnicodeUTF8));
        action_IGate_Stations_Query->setText(QApplication::translate("MainWindow", "&IGate Stations Query", 0, QApplication::UnicodeUTF8));
        action_WX_Stations_Query->setText(QApplication::translate("MainWindow", "&WX Stations Query", 0, QApplication::UnicodeUTF8));
        actionModify_Auto_Reply_Message->setText(QApplication::translate("MainWindow", "Modify &Auto Reply Message", 0, QApplication::UnicodeUTF8));
        actionEnable_Auto_Reply_Message->setText(QApplication::translate("MainWindow", "Enable Auto Reply Message", 0, QApplication::UnicodeUTF8));
        actionSatellite_Ack_Mode->setText(QApplication::translate("MainWindow", "Satellite Ack Mode", 0, QApplication::UnicodeUTF8));
        action_About->setText(QApplication::translate("MainWindow", "&About", 0, QApplication::UnicodeUTF8));
        actionHelp_Index->setText(QApplication::translate("MainWindow", "Help &Index", 0, QApplication::UnicodeUTF8));
        actionInterface_Control->setText(QApplication::translate("MainWindow", "Interface Control", 0, QApplication::UnicodeUTF8));
        actionDisable_Transmit_ALL->setText(QApplication::translate("MainWindow", "Disable Transmit: ALL", 0, QApplication::UnicodeUTF8));
        actionDisable_Transmit_My_Position->setText(QApplication::translate("MainWindow", "Disable Transmit: My Position", 0, QApplication::UnicodeUTF8));
        actionDisable_Transmit_Objects_Items->setText(QApplication::translate("MainWindow", "Disable Transmit: Objects/Items", 0, QApplication::UnicodeUTF8));
        actionEnable_Server_Ports->setText(QApplication::translate("MainWindow", "Enable Server Ports", 0, QApplication::UnicodeUTF8));
        action_Transmit_Now->setText(QApplication::translate("MainWindow", "&Transmit Now!", 0, QApplication::UnicodeUTF8));
        action_Fetch_GPS_Track->setText(QApplication::translate("MainWindow", "&Fetch GPS Track", 0, QApplication::UnicodeUTF8));
        actionFetch_GPS_Routes->setText(QApplication::translate("MainWindow", "Fetch GPS &Routes", 0, QApplication::UnicodeUTF8));
        actionFetch_GPS_Waypoints->setText(QApplication::translate("MainWindow", "Fetch GPS &Waypoints", 0, QApplication::UnicodeUTF8));
        actionFetch_Garmin_RINO_Waypoints->setText(QApplication::translate("MainWindow", "Fetch &Garmin RINO Waypoints", 0, QApplication::UnicodeUTF8));
        action_EMERGENCY_BEACON_MODE->setText(QApplication::translate("MainWindow", "!!! EMERGENCY BEACON MODE !!!", 0, QApplication::UnicodeUTF8));
        action_Station->setText(QApplication::translate("MainWindow", "&Station", 0, QApplication::UnicodeUTF8));
        action_Defaults->setText(QApplication::translate("MainWindow", "&Defaults", 0, QApplication::UnicodeUTF8));
        action_Timing->setText(QApplication::translate("MainWindow", "&Timing", 0, QApplication::UnicodeUTF8));
        actionC_oordinate_System->setText(QApplication::translate("MainWindow", "C&oordinate System", 0, QApplication::UnicodeUTF8));
        action_Audio_Alarms->setText(QApplication::translate("MainWindow", "&Audio Alarms", 0, QApplication::UnicodeUTF8));
        actionS_peech->setText(QApplication::translate("MainWindow", "S&peech", 0, QApplication::UnicodeUTF8));
        actionSmart_Beaconing->setText(QApplication::translate("MainWindow", "Smart Beaconing", 0, QApplication::UnicodeUTF8));
        actionFonts->setText(QApplication::translate("MainWindow", "Fonts", 0, QApplication::UnicodeUTF8));
        actionTest->setText(QApplication::translate("MainWindow", "&Test", 0, QApplication::UnicodeUTF8));
        actionChange_Debug_Level->setText(QApplication::translate("MainWindow", "Change &Debug Level", 0, QApplication::UnicodeUTF8));
        actionEnable_English_Units->setText(QApplication::translate("MainWindow", "Enable English Units", 0, QApplication::UnicodeUTF8));
        actionDist_Bearing_Status->setText(QApplication::translate("MainWindow", "Dist/Bearing Status", 0, QApplication::UnicodeUTF8));
        actionSave_Config_Now->setText(QApplication::translate("MainWindow", "Save &Config Now!", 0, QApplication::UnicodeUTF8));
        actionClose_Polygon->setText(QApplication::translate("MainWindow", "Close Polygon", 0, QApplication::UnicodeUTF8));
        actionErase_CAD_Polygons->setText(QApplication::translate("MainWindow", "Erase CAD Polygons", 0, QApplication::UnicodeUTF8));
        actionCAD_Polygons_2->setText(QApplication::translate("MainWindow", "CAD Polygons", 0, QApplication::UnicodeUTF8));
        actionEnable_CAD_objects->setText(QApplication::translate("MainWindow", "Enable CAD Objects", 0, QApplication::UnicodeUTF8));
        actionEnable_CAD_labels->setText(QApplication::translate("MainWindow", "Enable CAD Labels", 0, QApplication::UnicodeUTF8));
        actionEnable_CAD_probability->setText(QApplication::translate("MainWindow", "Enable CAD Probability", 0, QApplication::UnicodeUTF8));
        actionEnable_CAD_comments->setText(QApplication::translate("MainWindow", "Enable CAD Comments", 0, QApplication::UnicodeUTF8));
        actionEnable_CAD_area_size->setText(QApplication::translate("MainWindow", "Enable CAD Area Size", 0, QApplication::UnicodeUTF8));
        actionAdjust_Gamma_Correction->setText(QApplication::translate("MainWindow", "Adjust Gamma Correction", 0, QApplication::UnicodeUTF8));
        actionConfigure_Tigermap->setText(QApplication::translate("MainWindow", "Configure Tigermap", 0, QApplication::UnicodeUTF8));
        actionConfigure_USGS_DRG->setText(QApplication::translate("MainWindow", "Configure USGS DRG", 0, QApplication::UnicodeUTF8));
        actionRe_download_Maps_Not_from_cache->setText(QApplication::translate("MainWindow", "Re-download Maps (Not from cache)", 0, QApplication::UnicodeUTF8));
        actionFlush_Entire_Map_Cache->setText(QApplication::translate("MainWindow", "Flush Entire Map Cache!", 0, QApplication::UnicodeUTF8));
        actionIndex_New_Maps_on_Startup->setText(QApplication::translate("MainWindow", "Index New Maps on Startup", 0, QApplication::UnicodeUTF8));
        actionIndex_Add_New_Maps->setText(QApplication::translate("MainWindow", "Index: Add &New Maps", 0, QApplication::UnicodeUTF8));
        actionIndex_Reindex_ALL_Maps->setText(QApplication::translate("MainWindow", "Index: &Reindex ALL Maps!", 0, QApplication::UnicodeUTF8));
        actionWhite->setText(QApplication::translate("MainWindow", "White", 0, QApplication::UnicodeUTF8));
        actionBlack->setText(QApplication::translate("MainWindow", "Black", 0, QApplication::UnicodeUTF8));
        actionGray->setText(QApplication::translate("MainWindow", "Gray", 0, QApplication::UnicodeUTF8));
        actionMisty_Rose->setText(QApplication::translate("MainWindow", "Misty Rose", 0, QApplication::UnicodeUTF8));
        actionNavy_Blue->setText(QApplication::translate("MainWindow", "Navy Blue", 0, QApplication::UnicodeUTF8));
        actionSteel_Blue->setText(QApplication::translate("MainWindow", "Steel Blue", 0, QApplication::UnicodeUTF8));
        actionMed_Sea_Green->setText(QApplication::translate("MainWindow", "Medium Sea Green", 0, QApplication::UnicodeUTF8));
        actionPale_Green->setText(QApplication::translate("MainWindow", "Pale Green", 0, QApplication::UnicodeUTF8));
        actionPale_Goldenrod->setText(QApplication::translate("MainWindow", "Pale Goldenrod", 0, QApplication::UnicodeUTF8));
        actionGoldenrod_Yellow->setText(QApplication::translate("MainWindow", "Goldenrod Yellow", 0, QApplication::UnicodeUTF8));
        actionRosy_Brown->setText(QApplication::translate("MainWindow", "Rosy Brown", 0, QApplication::UnicodeUTF8));
        actionFirebrick_Red->setText(QApplication::translate("MainWindow", "Firebrick Red", 0, QApplication::UnicodeUTF8));
        action0->setText(QApplication::translate("MainWindow", "0%", 0, QApplication::UnicodeUTF8));
        action10->setText(QApplication::translate("MainWindow", "10%", 0, QApplication::UnicodeUTF8));
        action20->setText(QApplication::translate("MainWindow", "20%", 0, QApplication::UnicodeUTF8));
        action30->setText(QApplication::translate("MainWindow", "30%", 0, QApplication::UnicodeUTF8));
        action40->setText(QApplication::translate("MainWindow", "40%", 0, QApplication::UnicodeUTF8));
        action50->setText(QApplication::translate("MainWindow", "50%", 0, QApplication::UnicodeUTF8));
        action60->setText(QApplication::translate("MainWindow", "60%", 0, QApplication::UnicodeUTF8));
        action70->setText(QApplication::translate("MainWindow", "70%", 0, QApplication::UnicodeUTF8));
        action80->setText(QApplication::translate("MainWindow", "80%", 0, QApplication::UnicodeUTF8));
        action90->setText(QApplication::translate("MainWindow", "90%", 0, QApplication::UnicodeUTF8));
        action100->setText(QApplication::translate("MainWindow", "100%", 0, QApplication::UnicodeUTF8));
        action_Black_Border->setText(QApplication::translate("MainWindow", "&Black Border", 0, QApplication::UnicodeUTF8));
        actionBlack_Shadow->setText(QApplication::translate("MainWindow", "Black &Shadow", 0, QApplication::UnicodeUTF8));
        action_Text_on_Black->setText(QApplication::translate("MainWindow", "&Text on Black", 0, QApplication::UnicodeUTF8));
        action_No_Outline->setText(QApplication::translate("MainWindow", "&No Outline", 0, QApplication::UnicodeUTF8));
        action_Black_Outline->setText(QApplication::translate("MainWindow", "&Black Outline", 0, QApplication::UnicodeUTF8));
        action_Grey_Outline->setText(QApplication::translate("MainWindow", "&Grey Outline", 0, QApplication::UnicodeUTF8));
        action_White_Outline->setText(QApplication::translate("MainWindow", "&White Outline", 0, QApplication::UnicodeUTF8));
        actionExport_to_KML_File->setText(QApplication::translate("MainWindow", "Export to KML File", 0, QApplication::UnicodeUTF8));
        actionSelect_None->setText(QApplication::translate("MainWindow", "Select None", 0, QApplication::UnicodeUTF8));
        actionSelect_Mine->setText(QApplication::translate("MainWindow", "Select Mine", 0, QApplication::UnicodeUTF8));
        actionSelect_TNC->setText(QApplication::translate("MainWindow", "Select TNC", 0, QApplication::UnicodeUTF8));
        action_Select_Direct->setText(QApplication::translate("MainWindow", "- Select Direct", 0, QApplication::UnicodeUTF8));
        action_Select_Via_Digi->setText(QApplication::translate("MainWindow", "- Select Via Digi", 0, QApplication::UnicodeUTF8));
        actionSelect_Net->setText(QApplication::translate("MainWindow", "Select Net", 0, QApplication::UnicodeUTF8));
        actionSelect_Tactical_Calls_Only->setText(QApplication::translate("MainWindow", "Select Tactical Calls Only", 0, QApplication::UnicodeUTF8));
        actionInclude_Expired_Data->setText(QApplication::translate("MainWindow", "Include Expired Data", 0, QApplication::UnicodeUTF8));
        actionSelect_Stations->setText(QApplication::translate("MainWindow", "Select Stations", 0, QApplication::UnicodeUTF8));
        action_Select_Fixed_Stations->setText(QApplication::translate("MainWindow", "- Select Fixed Stations", 0, QApplication::UnicodeUTF8));
        action_Select_Moving_Stations->setText(QApplication::translate("MainWindow", "- Select Moving Stations", 0, QApplication::UnicodeUTF8));
        action_Select_WX_Stations->setText(QApplication::translate("MainWindow", "- Select WX Stations", 0, QApplication::UnicodeUTF8));
        action_Select_CWOP_WX_Stations->setText(QApplication::translate("MainWindow", "   - Select CWOP WX Stations", 0, QApplication::UnicodeUTF8));
        actionSelect_Objects_Items->setText(QApplication::translate("MainWindow", "Select Objects/Items", 0, QApplication::UnicodeUTF8));
        action_Select_WX_Objects_Items->setText(QApplication::translate("MainWindow", "- Select WX Objects/Items", 0, QApplication::UnicodeUTF8));
        action_Select_Water_Gauge_Objects_Items->setText(QApplication::translate("MainWindow", "- Select Water Gauge Objects/Items", 0, QApplication::UnicodeUTF8));
        action_Select_Other_Objects_Items->setText(QApplication::translate("MainWindow", "- Select Other Objects/Items", 0, QApplication::UnicodeUTF8));
        actionDisplay_Callsign->setText(QApplication::translate("MainWindow", "Display Callsign", 0, QApplication::UnicodeUTF8));
        action_Label_Trailpoints->setText(QApplication::translate("MainWindow", "- Label Trailpoints", 0, QApplication::UnicodeUTF8));
        actionDisplay_Symbol->setText(QApplication::translate("MainWindow", "Display Symbol", 0, QApplication::UnicodeUTF8));
        action_Rotate_Symbol->setText(QApplication::translate("MainWindow", "- Rotate Symbol", 0, QApplication::UnicodeUTF8));
        actionDisplay_Trail->setText(QApplication::translate("MainWindow", "Display Trail", 0, QApplication::UnicodeUTF8));
        actionDisplay_Course->setText(QApplication::translate("MainWindow", "Display Course", 0, QApplication::UnicodeUTF8));
        actionDisplay_Speed->setText(QApplication::translate("MainWindow", "Display Speed", 0, QApplication::UnicodeUTF8));
        action_Display_Short_Speed->setText(QApplication::translate("MainWindow", "- Display Short Speed", 0, QApplication::UnicodeUTF8));
        actionDisplay_Altitude->setText(QApplication::translate("MainWindow", "Display Altitude", 0, QApplication::UnicodeUTF8));
        actionDisplay_Weather_Info->setText(QApplication::translate("MainWindow", "Display Weather Info", 0, QApplication::UnicodeUTF8));
        action_Display_Weather_Text->setText(QApplication::translate("MainWindow", "- Display Weather Text", 0, QApplication::UnicodeUTF8));
        action_Temperature_Only->setText(QApplication::translate("MainWindow", "   - Temperature Only", 0, QApplication::UnicodeUTF8));
        action_Display_Wind_Barb->setText(QApplication::translate("MainWindow", "- Display Wind Barb", 0, QApplication::UnicodeUTF8));
        actionDisplay_Aloha_Circle->setText(QApplication::translate("MainWindow", "Display Aloha Circle", 0, QApplication::UnicodeUTF8));
        actionDisplay_Position_Ambiguity->setText(QApplication::translate("MainWindow", "Display Position Ambiguity", 0, QApplication::UnicodeUTF8));
        actionDisplay_Power_Gain->setText(QApplication::translate("MainWindow", "Display Power/Gain", 0, QApplication::UnicodeUTF8));
        action_Use_Default_Power_Gain->setText(QApplication::translate("MainWindow", "- Use Default Power/Gain", 0, QApplication::UnicodeUTF8));
        action_Display_Mobile_Power_Gain->setText(QApplication::translate("MainWindow", "- Display Mobile Power/Gain", 0, QApplication::UnicodeUTF8));
        actionDisplay_DF_Attributes->setText(QApplication::translate("MainWindow", "Display DF Attributes", 0, QApplication::UnicodeUTF8));
        actionDisplay_DF_Beamwidth->setText(QApplication::translate("MainWindow", "Display DF Beamwidth", 0, QApplication::UnicodeUTF8));
        actionDisplay_DF_Bearing->setText(QApplication::translate("MainWindow", "Display DF Bearing", 0, QApplication::UnicodeUTF8));
        actionEnable_Dead_Reckoning->setText(QApplication::translate("MainWindow", "Enable Dead-Reckoning", 0, QApplication::UnicodeUTF8));
        action_Display_Arc->setText(QApplication::translate("MainWindow", "- Display Arc", 0, QApplication::UnicodeUTF8));
        action_Display_Course->setText(QApplication::translate("MainWindow", "- Display Course", 0, QApplication::UnicodeUTF8));
        action_Display_Symbol->setText(QApplication::translate("MainWindow", "- Display Symbol", 0, QApplication::UnicodeUTF8));
        actionDIsplay_Dist_Bearing->setText(QApplication::translate("MainWindow", "DIsplay Dist/Bearing", 0, QApplication::UnicodeUTF8));
        actionDisplay_Last_Report_Age->setText(QApplication::translate("MainWindow", "Display Last Report Age", 0, QApplication::UnicodeUTF8));
        actionReload_Object_Item_History->setText(QApplication::translate("MainWindow", "Reload Object/Item History", 0, QApplication::UnicodeUTF8));
        actionClear_Object_Item_History->setText(QApplication::translate("MainWindow", "Clear Object/Item History", 0, QApplication::UnicodeUTF8));
        actionClear_All_Tactical_Calls->setText(QApplication::translate("MainWindow", "Clear All Tactical Calls", 0, QApplication::UnicodeUTF8));
        actionClear_Tactical_Call_History->setText(QApplication::translate("MainWindow", "Clear Tactical Call History", 0, QApplication::UnicodeUTF8));
        action_Clear_All_Trails->setText(QApplication::translate("MainWindow", "&Clear All Trails!!!", 0, QApplication::UnicodeUTF8));
        actionClear_All_Stations->setText(QApplication::translate("MainWindow", "Clear &All Stations!!!", 0, QApplication::UnicodeUTF8));
        incomingPackets->setText(QApplication::translate("MainWindow", "Packets go here...", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(Map1), QApplication::translate("MainWindow", "Map1", 0, QApplication::UnicodeUTF8));
        toolButton->setText(QApplication::translate("MainWindow", "...", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(Map2), QApplication::translate("MainWindow", "Map2", 0, QApplication::UnicodeUTF8));
        checkBox->setText(QApplication::translate("MainWindow", "CheckBox", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(Map3), QApplication::translate("MainWindow", "Map3", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(Map4), QApplication::translate("MainWindow", "Map4", 0, QApplication::UnicodeUTF8));
        menuFile->setTitle(QApplication::translate("MainWindow", "&File", 0, QApplication::UnicodeUTF8));
        menu_Configure->setTitle(QApplication::translate("MainWindow", "&Configure", 0, QApplication::UnicodeUTF8));
        menuView->setTitle(QApplication::translate("MainWindow", "&View", 0, QApplication::UnicodeUTF8));
        menuMap->setTitle(QApplication::translate("MainWindow", "&Map", 0, QApplication::UnicodeUTF8));
        menuDraw_CAD_Objects->setTitle(QApplication::translate("MainWindow", "Draw CAD Objects", 0, QApplication::UnicodeUTF8));
        menuConfigure->setTitle(QApplication::translate("MainWindow", "Configure", 0, QApplication::UnicodeUTF8));
        menuBackground_Color->setTitle(QApplication::translate("MainWindow", "Background &Color", 0, QApplication::UnicodeUTF8));
        menuMap_Intensity->setTitle(QApplication::translate("MainWindow", "Map &Intensity", 0, QApplication::UnicodeUTF8));
        menuStation_Text_Style->setTitle(QApplication::translate("MainWindow", "Station &Text Style", 0, QApplication::UnicodeUTF8));
        menuIcon_Outline_Style->setTitle(QApplication::translate("MainWindow", "Icon &Outline Style", 0, QApplication::UnicodeUTF8));
        menuStation->setTitle(QApplication::translate("MainWindow", "&Station", 0, QApplication::UnicodeUTF8));
        menu_Export_All->setTitle(QApplication::translate("MainWindow", "E&xport All", 0, QApplication::UnicodeUTF8));
        menuFilter_Data->setTitle(QApplication::translate("MainWindow", "Filter Data", 0, QApplication::UnicodeUTF8));
        menuFilter_Display->setTitle(QApplication::translate("MainWindow", "Filter Display", 0, QApplication::UnicodeUTF8));
        menuConfigure_2->setTitle(QApplication::translate("MainWindow", "&Configure", 0, QApplication::UnicodeUTF8));
        menuMessage->setTitle(QApplication::translate("MainWindow", "M&essage", 0, QApplication::UnicodeUTF8));
        menuInterface->setTitle(QApplication::translate("MainWindow", "&Interface", 0, QApplication::UnicodeUTF8));
        menuHelp->setTitle(QApplication::translate("MainWindow", "&Help", 0, QApplication::UnicodeUTF8));
        menu_EMERGENCY_BEACON_MODE_ENABLE->setTitle(QApplication::translate("MainWindow", "&EMERGENCY BEACON MODE ENABLE", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
