#! /bin/sh
#
# Copyright (C) 2000-2005  The Xastir Group
#
# Updated on 7/5/03 to reflect the new directory structure
# N0VH
#
XASTIR_BASE=/usr/local/share/xastir
cd /var/tmp
wget -c  --passive-ftp ftp://ftp.fcc.gov/pub/Bureaus/Wireless/Databases/uls/complete/l_amat.zip
unzip -p l_amat.zip EN.dat|sort +4 -t \| >$XASTIR_BASE/fcc/EN.dat
wget -c --passive-ftp ftp://ftp.rac.ca/pub/cdncaldb.zip
unzip cdncaldb.zip AMATEUR.RPT
mv AMATEUR.RPT $XASTIR_BASE/fcc/AMACALL.LST
rm l_amat.zip cdncaldb.zip
