#!/bin/sh

# $Id$
# Copyright (C) 2006  The Xastir Group

# The trick:  First compile Lesstif as an LSB package, installed at
# /opt/lsb-lesstif, using LSB-BUILD-LESSTIF script.  The commands
# below assume you've set up the directory structure at /opt/lsb
# specified at the top of that script.
#
# We should have /opt/lsb/lib.orig & /opt/lsb/lib.lesstif
# directories at this point along with a symlink from /opt/lsb/lib
# -> lib.lesstif:
#
#   cd /opt/lsb
#   cp -R lib.orig lib.xastir
#   rm lib                 (remove the symlink we created before)
#   ln -s lib.xastir lib   (link to the new directory)
#   cd lib
#   rm libXt.so            (or just "chmod 000 libXt.so")
#   cp PATH/libXt.a .      (special lib from LSB applib)
#   ln -s /opt/lsb-lesstif/lib/libXm.a
#
#   cd /opt/lsb
#   cp -R include include.xastir
#   mv include include.orig
#   ln -s include.xastir include  (link to the new directory)
#   cd include
#   ln -s /opt/lsb-lesstif/include/Xm
#
# This will allow us to statically link libraries without mucking
# around with the Makefiles.  When done compiling the LSB-Xastir
# package, put the /opt/lsb/lib directory back to normal by issuing
# these commands:
#
#  cd /opt/lsb
#  rm lib include             (remove the symlinks)
#  ln -s lib.orig lib         (link back to the original directory)
#  ln -s include.orig include (link back to the original directory)
#


./bootstrap.sh

export PATH=${PATH}:/opt/lsb/bin
export LSBCC_WARN=1

# A colon-separated list of "extra" shared libraries to link with
# the application.  Each shared lib must be LSB-compliant and must
# be distributed along with the application.
#export LSBCC_SHAREDLIBS=libXm.so

CC=lsbcc ./configure \
    --prefix=/opt/lsb-xastir \
    --with-lsb \
    --without-ax25 \
    --without-festival \
    --without-gpsman \
    --without-imagemagick \
    --without-libproj \
    --without-geotiff \
    --without-gdal \
    --with-internal-shapelib \
    --without-pcre \
    --without-dbfawk \
    --without-map_cache

make clean

find . -type f -name Makefile -print | while read i
  do
    sed -i 's/\/usr\/include/\/opt\/lsb\/include/g' $i
    sed -i 's/\/usr\/local\/include/\/opt\/lsb\/include/g' $i
    sed -i 's/\/usr\/X11R6\/include/\/opt\/lsb\/include/g' $i
    sed -i 's/\/usr\/lib/\/opt\/lsb\/lib/g' $i
    sed -i 's/\/usr\/X11R6\/lib/\/opt\/lsb\/lib/g' $i
    sed -i 's/\/usr\/X11\/lib/\/opt\/lsb\/lib/g' $i
    sed -i 's/\/usr\/X11\/include/\/opt\/lsb\/include/g' $i
    sed -i 's/\/usr\/local\/lib/\/opt\/lsb\/lib/g' $i
  done

(sudo make install 2>&1) | tee make.log


