#!/bin/sh

# $Id$
# Copyright (C) 2006  The Xastir Group

# Compile jasper-1.701.0 under Linux Standard Base 3.0.  Install
# into /opt/lsb-jasper/ directory structure.

export PATH=${PATH}:/opt/lsb/bin
export LSBCC_WARN=1

# A colon-separated list of "extra" shared libraries to link with
# the application.  Each shared lib must be LSB-compliant and must
# be distributed along with the application.
#export LSBCC_SHAREDLIBS=

CC=lsbcc CXX=lsbc++ ./configure \
    --prefix=/opt/lsb-tmp \
    --exec_prefix=/opt/lsb-tmp \
    --enable-static \
    --disable-shared

make clean

(make 2>&1) | tee make.log

#make -n install
sudo make install


