#!/bin/sh

# $Id$
# Copyright (C) 2006  The Xastir Group

# The trick:  First compile Lesstif as an LSB package, installed at
# /opt/lsb-lesstif, using LSB-BUILD-LESSTIF script.  The commands
# below assume you've set up the directory structure at /opt/lsb
# specified at the top of that script.
#
# We should have /opt/lsb/lib.orig & /opt/lsb/lib.lesstif
# directories at this point along with a symlink from /opt/lsb/lib
# -> lib.lesstif:
#
#   cd /opt/lsb
#   cp -R lib.orig lib.xastir
#   rm lib                 (remove the symlink we created before)
#   ln -s lib.xastir lib   (link to the new directory)
#   cd lib
#   rm libXt.so            (or just "chmod 000 libXt.so")
#   rm libz.so             (or just "chmod 000 libz.so")
#   cp PATH/libXt.a .      (lib from LSB CVS: "lsb/appbat" module)
#   ln -s /opt/lsb-lesstif/lib/libXm.a (from our Lesstif compile)
#   ln -s /opt/lsb-zlib/lib/libz.a
#   ln -s /opt/lsb-jpeg/lib/libjpeg.a
#   ln -s /opt/lsb-pcre/lib/libpcre.a
#   ln -s /opt/lsb-curl/lib/libcurl.a
#   ln -s /usr/local/lib/libtiff.a
#   ln -s /usr/local/lib/libproj.a
#   ln -s /usr/local/lib/libgeotiff.a
#   ln -s /opt/lsb-png/lib/libpng.a
#   ln -s /opt/lsb-jasper/lib/libjasper.a
#   ln -s /opt/lsb-graphicsmagick/lib/libGraphicsMagick.a libMagick.a
#
#   cd /opt/lsb
#   cp -R include include.xastir
#   mv include include.orig
#   ln -s include.xastir include  (link to the new directory)
#   cd include
#   ln -s /opt/lsb-lesstif/include/Xm (from our Lesstif compile)
#   ln -s /opt/lsb-pcre/include/pcre.h
#   ln -s /opt/lsb-curl/include/curl
#   ln -s /opt/lsb-png/include/png.h
#   ln -s /opt/lsb-jasper/include/jasper
#   ln -s /opt/lsb-graphicsmagick/include/GraphicsMagick/magick

# This will allow us to statically link libraries without mucking
# around with the Makefiles.  When done compiling the LSB-Xastir
# package, put the /opt/lsb/lib directory back to normal by issuing
# these commands:
#
#  cd /opt/lsb
#  rm lib include             (remove the symlinks)
#  ln -s lib.orig lib         (link back to the original directory)
#  ln -s include.orig include (link back to the original directory)
#


./bootstrap.sh

export PATH=${PATH}:/opt/lsb/bin
export LSBCC_WARN=1

# A colon-separated list of "extra" shared libraries to link with
# the application.  Each shared lib must be LSB-compliant and must
# be distributed along with the application.
#export LSBCC_SHAREDLIBS=libXm.so

CC=lsbcc ./configure \
    --prefix=/opt/lsb-xastir \
    --without-ax25 \
    --without-festival \
    --without-gpsman \
    --with-imagemagick \
    --with-proj \
    --with-geotiff \
    --without-gdal \
    --with-internal-shapelib \
    --with-pcre \
    --with-dbfawk \
    --without-map_cache \
    --with-rtree \
    --with-lsb

make clean

find . -type f -name Makefile -print | while read i
  do
    sed -i 's/\/usr\/include/\/opt\/lsb\/include/g' $i
    sed -i 's/\/usr\/local\/include/\/opt\/lsb\/include/g' $i
    sed -i 's/\/usr\/X11R6\/include/\/opt\/lsb\/include/g' $i
    sed -i 's/\/usr\/lib/\/opt\/lsb\/lib/g' $i
    sed -i 's/\/usr\/X11R6\/lib/\/opt\/lsb\/lib/g' $i
    sed -i 's/\/usr\/X11\/lib/\/opt\/lsb\/lib/g' $i
    sed -i 's/\/usr\/X11\/include/\/opt\/lsb\/include/g' $i
    sed -i 's/\/usr\/local\/lib/\/opt\/lsb\/lib/g' $i
  done

(make 2>&1) | tee make.log
strip src/xastir
strip src/xastir_udp_client
strip src/testawk
strip callpass/callpass
(sudo make install 2>&1) | tee install.log

/opt/lsb/bin/lsbappchk -A /opt/lsb-xastir/bin/xastir

#tar czf xastir.tgz /opt/lsb-xastir
#sudo rm -rf /usr/src/packages/SOURCES/xastir*
#sudo cp xastir.tgz /usr/src/packages/SOURCES/.
#rpmbuild -bb --clean xastir-lsb.spec

