#!/bin/sh

# $Id$
# Copyright (C) 2006  The Xastir Group

# Compile zlib-1.2.3 0 under Linux Standard Base 3.0.  Install into
# /opt/lsb-zlib/ directory structure.

export PATH=${PATH}:/opt/lsb/bin
export LSBCC_WARN=1

# A colon-separated list of "extra" shared libraries to link with
# the application.  Each shared lib must be LSB-compliant and must
# be distributed along with the application.
#export LSBCC_SHAREDLIBS=

# Patches to the source code:
#
sed -i -e 's/\$exec_prefix#/$prefix#/g' configure

CC=lsbcc CXX=lsbc++ ./configure \
    --prefix=/opt/lsb-zlib \
    --exec_prefix=/opt/lsb-zlib \
    --enable-static

make clean

(make 2>&1) | tee make.log

#make -n install prefix=/opt/lsb-zlib
sudo make install prefix=/opt/lsb-zlib


