#!/bin/sh

# $Id$
# Copyright (C) 2006  The Xastir Group

# Compile curl-7.16.0 under Linux Standard Base 3.0.  Install into
# /opt/lsb-curl/ directory structure.

export PATH=${PATH}:/opt/lsb/bin
export LSBCC_WARN=1

# A colon-separated list of "extra" shared libraries to link with
# the application.  Each shared lib must be LSB-compliant and must
# be distributed along with the application.
#export LSBCC_SHAREDLIBS=

CC=lsbcc ./configure \
    --prefix=/opt/lsb-curl \
    --exec_prefix=/opt/lsb-curl \
    --enable-static \
    --disable-ldap \
    --without-libidn

make clean

(make 2>&1) | tee make.log

#make -n install
sudo make install


