#!/bin/sh

# $Id$
# Copyright (C) 2006  The Xastir Group

# NOTE:
# "Free Standards Group, FSG, Linux Standard Base, LSB, Free
# Standards Certified, LSB Certified and the Free Standards
# Certified logo are trademarks, service marks and certification
# marks, as appropriate, of Free Standards Group in the United
# States and in other countries."
#
# We are in no way representing that Xastir has been certified by
# the FSG.  To do so costs real money.  We do intend some Xastir
# binaries to install and run properly on LSB-3.0 compliant x86
# Linux systems though...
#

# The trick:  First compile Lesstif as an LSB package, installed at
# /opt/lsb-tmp, using LSB-BUILD-LESSTIF script.  The commands
# below assume you've set up the directory structure at /opt/lsb
# specified at the top of that script.
#
# We should have /opt/lsb/lib.orig & /opt/lsb/lib.lesstif
# directories at this point along with a symlink from /opt/lsb/lib
# -> lib.lesstif:
#
#   cd /opt/lsb
#   cp -R lib.orig lib.xastir
#   rm lib                 (remove the symlink we created before)
#   ln -s lib.xastir lib   (link to the new directory)
#   cd lib
#   rm libXt.so            (or just "chmod 000 libXt.so")
#   rm libz.so             (or just "chmod 000 libz.so")
#   cp /home/src/lsb/libXt.a .      (lib from LSB CVS: "lsb/appbat" module)
#   ln -s /opt/lsb-tmp/lib/libXm.a (from our Lesstif compile)
#   ln -s /opt/lsb-tmp/lib/libz.a
#   ln -s /opt/lsb-tmp/lib/libjpeg.a
#   ln -s /opt/lsb-tmp/lib/libpcre.a
#   ln -s /opt/lsb-tmp/lib/libcurl.a
#   ln -s /usr/local/lib/libtiff.a
#   ln -s /usr/local/lib/libproj.a
#   ln -s /usr/local/lib/libgeotiff.a
#   ln -s /opt/lsb-tmp/lib/libpng.a
#   ln -s /opt/lsb-tmp/lib/libjasper.a
#   ln -s /opt/lsb-tmp/lib/libGraphicsMagick.a libMagick.a
#   ln -s /opt/lsb-tmp/lib/libdb.a
#
#   cd /opt/lsb
#   cp -R include include.xastir
#   mv include include.orig
#   ln -s include.xastir include  (link to the new directory)
#   cd include
#   ln -s /opt/lsb-tmp/include/Xm (from our Lesstif compile)
#   ln -s /opt/lsb-tmp/include/pcre.h
#   ln -s /opt/lsb-tmp/include/curl
#   ln -s /opt/lsb-tmp/include/png.h
#   ln -s /opt/lsb-tmp/include/jasper
#   rm zlib.h
#   ln -s /opt/lsb-tmp/include/zlib.h
#   ln -s /opt/lsb-tmp/include/zconf.h
#   ln -s /opt/lsb-tmp/include/GraphicsMagick/magick
#   ln -s /opt/lsb-tmp/include/db.h

# This will allow us to statically link libraries without mucking
# around with the Makefiles.  When done compiling the LSB-Xastir
# package, put the /opt/lsb/lib directory back to normal by issuing
# these commands:
#
#  cd /opt/lsb
#  rm lib include             (remove the symlinks)
#  ln -s lib.orig lib         (link back to the original directory)
#  ln -s include.orig include (link back to the original directory)
#


./bootstrap.sh

export PATH=${PATH}:/opt/lsb/bin
export LSBCC_WARN=1

# A colon-separated list of "extra" shared libraries to link with
# the application.  Each shared lib must be LSB-compliant and must
# be distributed along with the application.
#export LSBCC_SHAREDLIBS=libXm.so

CC=lsbcc CXX=lsbc++ ./configure \
    --prefix=/opt/Xastir \
    --without-ax25 \
    --without-festival \
    --without-gpsman \
    --with-imagemagick \
    --with-proj \
    --with-geotiff \
    --without-gdal \
    --with-internal-shapelib \
    --with-pcre \
    --with-dbfawk \
    --with-map_cache \
    --with-rtree \
    --with-lsb

make clean

find . -type f -name Makefile -print | while read i
  do
    sed -i 's@/usr/include@/opt/lsb/include@g' $i
    sed -i 's@/usr/local/include@/opt/lsb/include@g' $i
    sed -i 's@/usr/X11R6/include@/opt/lsb/include@g' $i
    sed -i 's@/usr/lib@/opt/lsb/lib@g' $i
    sed -i 's@/usr/X11R6/lib@/opt/lsb/lib@g' $i
    sed -i 's@/usr/X11/lib@/opt/lsb/lib@g' $i
    sed -i 's@/usr/X11/include@/opt/lsb/include@g' $i
    sed -i 's@/usr/local/lib@/opt/lsb/lib@g' $i
  done

(make 2>&1) | tee make.log
strip src/xastir
strip src/xastir_udp_client
strip src/testawk
strip callpass/callpass
(sudo make install 2>&1) | tee install.log

# Copy GraphicsMagick "gm" binary to the Xastir area
sudo /bin/cp /opt/lsb-tmp/bin/gm /opt/Xastir/bin/.

/opt/lsb/bin/lsbappchk -A -j /dev/null /opt/Xastir/bin/xastir
/opt/lsb/bin/lsbappchk -A -j /dev/null /opt/Xastir/bin/callpass
/opt/lsb/bin/lsbappchk -A -j /dev/null /opt/Xastir/bin/xastir_udp_client
/opt/lsb/bin/lsbappchk -A -j /dev/null /opt/Xastir/bin/gm

#tar czf xastir.tgz /opt/Xastir
#sudo rm -rf /usr/src/packages/SOURCES/xastir*
#sudo cp xastir.tgz /usr/src/packages/SOURCES/.
#rpmbuild -bb --clean xastir-lsb.spec

tar cjf xastir-lsb-1.8.5.tar.bz2 /opt/Xastir
#scp xastir-lsb-1.8.5.tar.bz2 eskimo:ftp/aprs/xastir/LSB/.


