#!/bin/sh

# $Id$
# Copyright (C) 2006-2010  The Xastir Group
# <http://www.zlib.net/>

# Compile zlib-1.2.3 0 under Linux Standard Base 3.0.  Install into
# /opt/lsb-tmp/ directory structure.

# NOTE:
# "Free Standards Group, FSG, Linux Standard Base, LSB, Free
# Standards Certified, LSB Certified and the Free Standards
# Certified logo are trademarks, service marks and certification
# marks, as appropriate, of Free Standards Group in the United
# States and in other countries."
#
# We are in no way representing that Xastir has been certified by
# the FSG.  To do so costs real money.  We do intend some Xastir
# binaries to install and run properly on LSB-3.0 compliant x86
# Linux systems though...
#

export PATH=${PATH}:/opt/lsb/bin
export LSBCC_WARN=1

# A colon-separated list of "extra" shared libraries to link with
# the application.  Each shared lib must be LSB-compliant and must
# be distributed along with the application.
#export LSBCC_SHAREDLIBS=

# Patches to the source code:
#
sed -i -e 's/\$exec_prefix#/$prefix#/g' configure

CC=lsbcc CXX=lsbc++ ./configure \
    --prefix=/opt/lsb-tmp \
    --exec_prefix=/opt/lsb-tmp \
    --enable-static

make clean

(make 2>&1) | tee make.log

#make -n install prefix=/opt/lsb-tmp
sudo make install prefix=/opt/lsb-tmp


