PROJ_DIR = 	D:\warmerda\proj

CFLAGS	=	/I.. /I$(PROJ_DIR)\src /D_LITTLE_ENDIAN -DPROJ4 

LINKARGS =	..\shpopen.obj ..\dbfopen.obj \
		D:\warmerda\proj\src\proj_i.lib

default:	all

all:	shpcat.exe shpdxf.exe shpinfo.exe

shpcat.exe:	shpcat.obj
	$(CC) $(CFLAGS) shpcat.obj  $(LINKARGS) 

shpdxf.exe:	shpdxf.obj
	$(CC) $(CFLAGS) shpdxf.obj  $(LINKARGS) 

shpinfo.exe:	shpinfo.obj
	$(CC) $(CFLAGS) shpinfo.obj  $(LINKARGS) 

clean:
	del *.obj *.exe

