name: Basic Ubuntu Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Update Packages
      run: sudo apt-get update
    - name: Install Packages
      run: sudo apt-get install -y graphicsmagick libgraphicsmagick1-dev libmotif-dev libcurl4-openssl-dev libpcre3-dev libdb-dev shapelib libshp-dev libxpm-dev
    - name: Bootstrap
      run: ./bootstrap.sh
    - name: configure
      run: ./configure CPPFLAGS="-I/usr/include/geotiff"
    - name: make
      run: make
    - name: make install
      run: sudo make install
